import {
  extendZodWithOpenApi,
  OpenAPIRegistry,
  OpenApiGeneratorV31,
  type RouteConfig,
} from "@asteasolutions/zod-to-openapi";
import { Problem, ProblemCategory } from "@croco/problems-core";
import {
  assertContractGraphHasNoErrors,
  buildContractGraph,
  type ContractGraph,
  type ContractGraphRoute,
  type ParamIR,
} from "@croco/protocols-core";
import { type ZodType, z } from "zod";

extendZodWithOpenApi(z);

const HTTP_METHODS = ["get", "post", "put", "delete", "patch", "head", "options", "trace"] as const;

type OpenAPIDocument = ReturnType<OpenApiGeneratorV31["generateDocument"]>;
type OpenAPIConfig = Parameters<OpenApiGeneratorV31["generateDocument"]>[0];
type OpenAPIComponents = NonNullable<OpenAPIDocument["components"]>;
type HttpMethod = (typeof HTTP_METHODS)[number];
type ControllerConstructor = new (...args: unknown[]) => unknown;
type OpenAPIParamLocation = "path" | "query" | "header";
type OpenAPIReference = { $ref: string };
type RouteResponses = RouteConfig["responses"];

export type ProblemResponseConfig = {
  readonly status: number | `${number}` | "default";
  readonly description: string;
};

export type EmitOpenAPIOptions = {
  readonly info?: Partial<OpenAPIConfig["info"]>;
  readonly servers?: OpenAPIConfig["servers"];
  readonly security?: OpenAPIConfig["security"];
  readonly securitySchemes?: OpenAPIComponents["securitySchemes"];
  readonly tags?: OpenAPIConfig["tags"];
  readonly defaultResponses?: RouteResponses;
  readonly problemResponses?: readonly ProblemResponseConfig[];
};

const DEFAULT_INFO: OpenAPIConfig["info"] = {
  title: "Croco API",
  version: "1.0.0",
  license: {
    name: "MIT",
    identifier: "MIT",
  },
};

const DEFAULT_SERVERS: OpenAPIConfig["servers"] = [{ url: "/" }];

const DEFAULT_PROBLEM_RESPONSES = [
  { status: 400, description: "Bad request" },
  { status: 422, description: "Validation error" },
  { status: 500, description: "Internal server error" },
] as const satisfies readonly ProblemResponseConfig[];

class OpenAPIContractProblem extends Problem {
  constructor(detail: string) {
    super("openapi-spec/invalid-contract", ProblemCategory.ValidationError, detail);
  }
}

export function emitOpenAPI(
  controllers: Function[],
  options: EmitOpenAPIOptions = {},
): OpenAPIDocument {
  return emitOpenAPIFromContractGraph(
    buildContractGraph(controllers as ControllerConstructor[]),
    options,
  );
}

export function emitOpenAPIFromContractGraph(
  graph: ContractGraph,
  options: EmitOpenAPIOptions = {},
): OpenAPIDocument {
  assertContractGraphHasNoErrors(graph);

  const registry = new OpenAPIRegistry();
  const routes = [...graph.routes];
  const problemDetailsRef = registerProblemDetailsSchema(registry);
  const defaultResponses = toDefaultResponses(options, problemDetailsRef);

  registerSecuritySchemes(registry, options.securitySchemes);

  routes.forEach((route) => {
    registry.registerPath(toRouteConfig(route, defaultResponses));
  });

  const generator = new OpenApiGeneratorV31(registry.definitions);

  return generator.generateDocument({
    openapi: "3.1.0",
    info: { ...DEFAULT_INFO, ...options.info },
    servers: options.servers ?? DEFAULT_SERVERS,
    security: options.security ?? [],
    tags: options.tags ?? toTags(routes),
  });
}

function registerProblemDetailsSchema(registry: OpenAPIRegistry): OpenAPIReference {
  const { ref } = registry.registerComponent("schemas", "ProblemDetails", {
    type: "object",
    description: "RFC 7807 Problem Details response body.",
    required: ["type", "title", "status", "code"],
    properties: {
      type: {
        type: "string",
        description: "A URI reference that identifies the problem type.",
        example: "about:blank",
      },
      title: {
        type: "string",
        description: "A short, human-readable summary of the problem type.",
        example: "Bad Request",
      },
      status: {
        type: "integer",
        description: "The HTTP status code generated by the origin server.",
        example: 400,
      },
      code: {
        type: "string",
        description: "Croco domain-specific problem code.",
        example: "validation/request-invalid",
      },
      detail: {
        type: "string",
        description: "A human-readable explanation specific to this occurrence.",
      },
      instance: {
        type: "string",
        description: "A URI reference that identifies this occurrence of the problem.",
      },
    },
    additionalProperties: true,
  });

  return ref;
}

function registerSecuritySchemes(
  registry: OpenAPIRegistry,
  securitySchemes: EmitOpenAPIOptions["securitySchemes"],
): void {
  if (!securitySchemes) {
    return;
  }

  for (const [name, securityScheme] of Object.entries(securitySchemes)) {
    registry.registerComponent("securitySchemes", name, securityScheme);
  }
}

function toDefaultResponses(
  options: EmitOpenAPIOptions,
  problemDetailsRef: OpenAPIReference,
): RouteResponses {
  return {
    ...toProblemResponseConfig(
      options.problemResponses ?? DEFAULT_PROBLEM_RESPONSES,
      problemDetailsRef,
    ),
    ...options.defaultResponses,
  };
}

function toProblemResponseConfig(
  responses: readonly ProblemResponseConfig[],
  problemDetailsRef: OpenAPIReference,
): RouteResponses {
  return Object.fromEntries(
    responses.map((response) => [
      String(response.status),
      {
        description: response.description,
        content: {
          "application/problem+json": {
            schema: problemDetailsRef,
          },
        },
      },
    ]),
  );
}

function toRouteConfig(route: ContractGraphRoute, defaultResponses: RouteResponses): RouteConfig {
  return {
    method: toHttpMethod(route),
    path: toOpenAPIPath(route.path),
    operationId: route.operationId,
    summary: route.routeId,
    tags: [route.domain ?? route.controllerName],
    responses: toResponseConfig(route, defaultResponses),
    ...(route.params.length > 0 || route.inputSchema ? { request: toRequestConfig(route) } : {}),
  };
}

function toResponseConfig(
  route: ContractGraphRoute,
  defaultResponses: RouteResponses,
): RouteResponses {
  const outputSchema = unwrapZodEffects(route.outputSchema);

  return {
    ...defaultResponses,
    200: {
      description: "Successful response",
      ...(outputSchema
        ? {
            content: {
              "application/json": {
                schema: outputSchema,
              },
            },
          }
        : {}),
    },
  };
}

function toTags(routes: ContractGraphRoute[]): { name: string; description: string }[] {
  const tagNames = new Set(routes.map((route) => route.domain ?? route.controllerName));

  return [...tagNames].map((name) => ({
    name,
    description: `${name} operations`,
  }));
}

function toRequestConfig(route: ContractGraphRoute): RouteConfig["request"] {
  const params = toZodObject(route.params.filter((param) => param.kind === "path"));
  const query = toZodObject(route.params.filter((param) => param.kind === "query"));
  const headers = toZodObject(route.params.filter((param) => param.kind === "header"));
  const bodySchema = unwrapZodEffects(
    route.inputSchema ?? route.params.find((param) => param.kind === "body")?.schema,
  );

  return {
    ...(bodySchema
      ? {
          body: {
            required: true,
            content: {
              "application/json": {
                schema: bodySchema,
              },
            },
          },
        }
      : {}),
    ...(params ? { params } : {}),
    ...(query ? { query } : {}),
    ...(headers ? { headers } : {}),
  };
}

function toZodObject(params: ParamIR[]): z.ZodObject<Record<string, ZodType>> | undefined {
  if (params.length === 0) {
    return undefined;
  }

  const shape = Object.fromEntries(
    params.map((param) => [param.name, withParameterMetadata(param)]),
  );

  return z.object(shape);
}

function withParameterMetadata(param: ParamIR): ZodType {
  const schema = unwrapZodEffects(param.schema) ?? z.string();
  const location = toOpenAPIParamLocation(param.kind);

  return schema.openapi({
    param: {
      name: param.name,
      in: location,
      required: param.kind === "path",
    },
  });
}

function unwrapZodEffects(schema: ZodType | null | undefined): ZodType | null | undefined {
  if (!schema || !(schema instanceof z.ZodEffects)) {
    return schema;
  }

  return unwrapZodEffects(schema.innerType());
}

function toOpenAPIParamLocation(kind: ParamIR["kind"]): OpenAPIParamLocation {
  if (kind === "path" || kind === "query" || kind === "header") {
    return kind;
  }

  throw new OpenAPIContractProblem(`Unsupported OpenAPI parameter kind: ${kind}`);
}

function toOpenAPIPath(path: string): string {
  return path.replace(/:([^/]+)/g, "{$1}");
}

function toHttpMethod(route: ContractGraphRoute): HttpMethod {
  const method = route.httpMethod;
  const normalizedMethod = method.toLowerCase();
  const httpMethod = HTTP_METHODS.find((candidate) => candidate === normalizedMethod);

  if (httpMethod) {
    return httpMethod;
  }

  if (normalizedMethod === "all") {
    throw new OpenAPIContractProblem(
      `Cannot emit OpenAPI operation for @All route ${formatRoute(route)}: @All is runtime-only and cannot be represented as a concrete OpenAPI operation. Use explicit HTTP method decorators for generated contracts.`,
    );
  }

  throw new OpenAPIContractProblem(`Unsupported HTTP method: ${method}`);
}

function formatRoute(route: ContractGraphRoute): string {
  return `${route.controllerName}.${route.methodName} (${route.path})`;
}
