export type EnvironmentVariableCatalogEntry = {
  readonly description: string;
  readonly secret: boolean;
  readonly example?: string;
};

export const ENVIRONMENT_VARIABLE_CATALOG = {
  AWS_REGION: {
    description: "AWS region for Lambda deployment.",
    secret: false,
    example: "ap-northeast-2",
  },
  BETTER_AUTH_SECRET: {
    description: "Better Auth signing secret.",
    secret: true,
  },
  BETTER_AUTH_URL: {
    description: "Public API origin used by Better Auth callbacks.",
    secret: false,
  },
  CLERK_SECRET_KEY: {
    description: "Clerk backend secret key.",
    secret: true,
  },
  CLOUDFLARE_ACCOUNT_ID: {
    description: "Cloudflare account id for Workers and R2.",
    secret: true,
  },
  CLOUDFLARE_API_TOKEN: {
    description: "Cloudflare deploy token.",
    secret: true,
  },
  CLOUDINARY_URL: {
    description: "Cloudinary URL for generated object storage.",
    secret: true,
  },
  DATABASE_URL: {
    description: "Database connection URL.",
    secret: true,
  },
  GRAPHQL_AUTH_TOKEN: {
    description: "Bearer token accepted by the generated GraphQL auth guard.",
    secret: true,
  },
  NEXT_PUBLIC_API_URL: {
    description: "Public API URL used by the generated Next.js client.",
    secret: false,
    example: "http://localhost:3000",
  },
  NODE_ENV: {
    description: "Runtime environment used for production defaults and telemetry sampling.",
    secret: false,
    example: "development",
  },
  OTEL_EXPORTER_OTLP_ENDPOINT: {
    description: "OTLP endpoint used by telemetry init and flush.",
    secret: false,
    example: "http://localhost:4318",
  },
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {
    description: "Optional trace-specific OTLP endpoint that overrides the shared OTLP endpoint.",
    secret: false,
    example: "http://localhost:4318/v1/traces",
  },
  POLAR_ACCESS_TOKEN: {
    description: "Polar API access token.",
    secret: true,
  },
  POLAR_PRODUCT_ID_TEAM: {
    description: "Polar product id for the team plan.",
    secret: false,
  },
  POLAR_WEBHOOK_SECRET: {
    description: "Polar webhook signature secret.",
    secret: true,
  },
  PORT: {
    description: "Port used by the generated Node API server.",
    secret: false,
    example: "3000",
  },
  R2_BUCKET: {
    description: "R2 bucket name for object storage.",
    secret: false,
  },
  SAAS_DEMO_ENDPOINTS_ENABLED: {
    description: "Opt-in local HTTP demo endpoints.",
    secret: false,
    example: "false",
  },
  SAAS_PROVIDER_PROFILE: {
    description: "Selected generated provider profile name.",
    secret: false,
  },
  TELEMETRY_ENABLED: {
    description: "Enable OpenTelemetry exporter wiring.",
    secret: false,
    example: "false",
  },
  UPSTASH_QSTASH_CURRENT_SIGNING_KEY: {
    description: "Current QStash webhook signing key.",
    secret: true,
  },
  UPSTASH_QSTASH_NEXT_SIGNING_KEY: {
    description: "Next QStash webhook signing key.",
    secret: true,
  },
  UPSTASH_QSTASH_TOKEN: {
    description: "QStash token for task delivery.",
    secret: true,
  },
  UPSTASH_REDIS_REST_TOKEN: {
    description: "Upstash Redis REST token.",
    secret: true,
  },
  UPSTASH_REDIS_REST_URL: {
    description: "Upstash Redis REST URL for metering state.",
    secret: true,
  },
  VITE_API_URL: {
    description: "Public API URL used by the generated Vite client.",
    secret: false,
    example: "http://localhost:3000",
  },
  WEB_ORIGIN: {
    description: "Browser origin allowed by the generated API CORS policy.",
    secret: false,
    example: "http://localhost:5173",
  },
} as const satisfies Record<string, EnvironmentVariableCatalogEntry>;

export type EnvironmentVariableName = keyof typeof ENVIRONMENT_VARIABLE_CATALOG;

export type EnvironmentTemplateVariable = EnvironmentVariableCatalogEntry & {
  readonly name: EnvironmentVariableName;
  readonly example?: string;
};

type EnvironmentTemplateSection = {
  readonly title: string;
  readonly description?: string;
  readonly variables: readonly EnvironmentTemplateVariable[];
};

export type EnvironmentTemplateCapabilities = {
  readonly scaffold: "blank" | "ddd" | "production-app" | "admin-console";
  readonly graphqlAuth: boolean;
  readonly nextjsApiClient: boolean;
  readonly viteApiClient: boolean;
  readonly workerRuntime: boolean;
};

type SaasEnvironmentManifest = {
  readonly profile: {
    readonly name: string;
  };
  readonly env: {
    readonly required: readonly EnvironmentTemplateVariable[];
    readonly optional: readonly EnvironmentTemplateVariable[];
  };
};

const HEADER = [
  "# Generated by create-croco-app.",
  "# Copy this file to .env and uncomment only the variables your application uses.",
  "# Keep .env and real credentials out of version control.",
  "# Extend this template when you add integrations; use package documentation as the source of truth.",
] as const;

const DDD_DATABASE_SECTION = section("Database", ["DATABASE_URL"]);
const GRAPHQL_AUTH_SECTION = section("GraphQL authentication", ["GRAPHQL_AUTH_TOKEN"]);
const NEXT_PUBLIC_API_SECTION = section("Next.js API client", ["NEXT_PUBLIC_API_URL"]);
const VITE_API_SECTION = section("Vite API client", ["VITE_API_URL"]);
const WORKER_RUNTIME_SECTION = section("Worker runtime", ["WEB_ORIGIN"]);
const PRODUCTION_RUNTIME_SECTION = section("API runtime", ["NODE_ENV", "PORT", "WEB_ORIGIN"]);
const TELEMETRY_SECTION = section("Telemetry", [
  "TELEMETRY_ENABLED",
  "OTEL_EXPORTER_OTLP_ENDPOINT",
  "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
]);
const ADMIN_CONSOLE_SECTION: EnvironmentTemplateSection = {
  title: "Admin console providers",
  description:
    "The generated admin console uses in-memory and fake providers. Add provider variables here only after selecting a production integration.",
  variables: [],
};

export function getEnvironmentVariable(
  name: EnvironmentVariableName,
  example?: string,
): EnvironmentTemplateVariable {
  const catalogEntry = ENVIRONMENT_VARIABLE_CATALOG[name];

  return {
    name,
    ...catalogEntry,
    ...(example === undefined ? {} : { example }),
  };
}

export function renderEnvironmentTemplate(capabilities: EnvironmentTemplateCapabilities): string {
  if (capabilities.scaffold === "blank") {
    return renderSections([]);
  }

  if (capabilities.scaffold === "production-app") {
    return renderSections([PRODUCTION_RUNTIME_SECTION, TELEMETRY_SECTION, VITE_API_SECTION]);
  }

  if (capabilities.scaffold === "admin-console") {
    return renderSections([
      PRODUCTION_RUNTIME_SECTION,
      TELEMETRY_SECTION,
      VITE_API_SECTION,
      ADMIN_CONSOLE_SECTION,
    ]);
  }

  const sections: EnvironmentTemplateSection[] = [DDD_DATABASE_SECTION];

  if (capabilities.graphqlAuth) {
    sections.push(GRAPHQL_AUTH_SECTION);
  }

  if (capabilities.workerRuntime) {
    sections.push(WORKER_RUNTIME_SECTION);
  }

  if (capabilities.nextjsApiClient) {
    sections.push(NEXT_PUBLIC_API_SECTION);
  }

  if (capabilities.viteApiClient) {
    sections.push(VITE_API_SECTION);
  }

  return renderSections(sections);
}

export function renderSaasEnvironmentTemplate(manifest: SaasEnvironmentManifest): string {
  return renderSections(
    [
      {
        title: "SaaS provider profile",
        description:
          "All values stay commented until real-provider mode is intentionally configured.",
        variables: [...manifest.env.required, ...manifest.env.optional],
      },
    ],
    manifest.profile.name,
  );
}

export function renderEnvironmentTemplateSnapshot(
  template: "blank" | "base-ddd" | "spa-be-split" | "admin-console",
): string {
  if (template === "blank") return renderSections([]);
  if (template === "base-ddd") return renderSections([DDD_DATABASE_SECTION]);
  if (template === "spa-be-split") {
    return renderSections([PRODUCTION_RUNTIME_SECTION, TELEMETRY_SECTION, VITE_API_SECTION]);
  }

  return renderSections([
    PRODUCTION_RUNTIME_SECTION,
    TELEMETRY_SECTION,
    VITE_API_SECTION,
    ADMIN_CONSOLE_SECTION,
  ]);
}

function section(
  title: string,
  variableNames: readonly EnvironmentVariableName[],
): EnvironmentTemplateSection {
  return {
    title,
    variables: variableNames.map((name) => getEnvironmentVariable(name)),
  };
}

function renderSections(
  sections: readonly EnvironmentTemplateSection[],
  profileName?: string,
): string {
  return [
    ...HEADER,
    ...sections.flatMap((environmentSection) => [
      "",
      `# -- ${environmentSection.title} --`,
      ...(environmentSection.description === undefined
        ? []
        : [`# ${environmentSection.description}`]),
      ...environmentSection.variables.flatMap((variable) => [
        `# ${variable.description}`,
        `# ${variable.name}=${renderExampleValue(variable, profileName)}`,
      ]),
    ]),
    "",
  ].join("\n");
}

function renderExampleValue(variable: EnvironmentTemplateVariable, profileName?: string): string {
  if (variable.name === "SAAS_PROVIDER_PROFILE" && profileName !== undefined) {
    return profileName;
  }

  if (variable.example !== undefined) {
    return variable.example;
  }

  return variable.secret ? `<croco-secret:${variable.name}>` : `<croco-config:${variable.name}>`;
}
