import { readControllerMetadata } from './metadata-reader';
import type { CompiledRouteInfo } from './metadata-reader';

export type CompiledController = {
  readonly basePath: string;
  readonly className?: string;
  readonly routes: readonly CompiledRouteInfo[];
};

type CompileRoutesOptions = {
  readonly controllerPaths: readonly string[];
  readonly outputDir: string;
};

function joinRoutePath(basePath: string, routePath: string): string {
  const fullPath = `${basePath}${routePath}`;
  return fullPath || '/';
}

function formatRegistration(controller: CompiledController, route: CompiledRouteInfo, responseText: string): string {
  const fullPath = joinRoutePath(controller.basePath, route.path);
  const className = controller.className ?? 'Controller';
  return `  app.${route.method.toLowerCase()}('${fullPath}', /* ${className}.${route.handlerName} */ (c) => c.text('${responseText}'));`;
}

export function generateRouteRegistrationCode(controllers: readonly CompiledController[]): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by @croco/framework-routes compiler');
  lines.push('// Do not edit manually');
  lines.push('');

  for (const controller of controllers) {
    for (const route of controller.routes) {
      lines.push(formatRegistration(controller, route, 'route compiled'));
    }
  }

  return lines.join('\n');
}

export function generateModule(controllers: readonly CompiledController[]): string {
  const lines: string[] = [];

  lines.push('// Auto-generated by @croco/framework-routes compiler');
  lines.push('// Do not edit manually');
  lines.push('');
  lines.push('export function registerRoutes(app) {');

  for (const controller of controllers) {
    for (const route of controller.routes) {
      lines.push(formatRegistration(controller, route, 'ok'));
    }
  }

  lines.push('}');
  return lines.join('\n');
}

export async function compileRoutes(options: CompileRoutesOptions): Promise<void> {
  const controllers: CompiledController[] = [];

  for (const controllerPath of options.controllerPaths) {
    const info = await readControllerMetadata(controllerPath);

    if (info) {
      controllers.push({ basePath: info.basePath, className: info.className, routes: info.routes });
    }
  }

  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const outDir = path.join(options.outputDir, '.croco', 'build');

  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'routes.js'), generateModule(controllers), 'utf-8');
}
