/**
 * @croco/admin-react
 *
 * Provider-neutral React primitives and contracts for SaaS billing, entitlement,
 * quota, usage, and provider status administration.
 */

export {
  AdminForm,
  AdminFormField,
  AdminFormGlobalProblem,
  AdminFormRecoveryActions,
  AdminActionList,
  BillingEntitlementAdminPanel,
  BillingStatus,
  EntitlementList,
  ImpersonationBanner,
  PlanSummary,
  PermissionInspector,
  ProblemNotice,
  TenantImpersonationConsole,
  TenantSwitcher,
  UsageQuotaMeter,
} from "./libs/components";
export {
  createTenantWorkspaceActionRequest,
  TenantBusinessWorkspace,
} from "./libs/TenantBusinessWorkspace";
export { WebhookReliabilityConsole } from "./libs/WebhookReliabilityConsole";
export {
  LifecycleAutomationConsole,
  LifecycleDryRunPanel,
  LifecycleRuleOperations,
  LifecycleRunHistory,
} from "./libs/LifecycleAutomationConsole";
export {
  classifyLifecycleRun,
  createLifecycleAutomationLoadingState,
  createLifecycleAutomationSource,
  diffLifecycleRuleDescriptors,
  loadLifecycleAutomationConsole,
} from "./libs/lifecycleAutomation";
export { useAdminForm } from "./libs/hooks";
export { AdminDataTable } from "./libs/DataTable";
export {
  createAdminDataTableInvalidRowIdProblemDetails,
  createAdminDataTableListResult,
  createAdminDataTableListResultFromCursorPage,
  createAdminDataTableListResultFromOffsetPage,
  createAdminDataTableListResultFromSearchResult,
  createAdminDataTablePermissionDeniedProblemDetails,
  createAdminDataTableState,
} from "./libs/dataTableSnapshot";
export {
  createAdminFormState,
  createBillingEntitlementAdminPanelState,
  createCoreProblemDetails,
  createImpersonationExpiredProblemDetails,
  createInMemoryAdminFormState,
  createInMemoryBillingEntitlementAdminPanelState,
  createInMemoryTenantImpersonationConsoleState,
  createPermissionInspectionProblemDetails,
  createPermissionInspectionUnavailableProblemDetails,
  createPermissionDeniedProblemDetails,
  createTenantImpersonationConsoleState,
  createTenantUnavailableProblemDetails,
  evaluateAdminActionPermissions,
  resetAdminFormState,
  submitAdminForm,
  updateAdminFormField,
} from "./libs/snapshot";
export type {
  AdminActionContract,
  AdminActionPermissionDecision,
  AdminActionSource,
  AdminAuditMetadata,
  AdminBillingStatus,
  AdminEntitlementRow,
  AdminImpersonationActiveInput,
  AdminImpersonationActiveState,
  AdminImpersonationConsoleState,
  AdminImpersonationExpiredInput,
  AdminImpersonationExpiredState,
  AdminImpersonationInactiveInput,
  AdminImpersonationInactiveState,
  AdminImpersonationPrincipal,
  AdminImpersonationStateInput,
  AdminImpersonationUnavailableInput,
  AdminImpersonationUnavailableState,
  AdminFormContract,
  AdminFormController,
  AdminFormFieldChangeHandler,
  AdminFormFieldContract,
  AdminFormFieldError,
  AdminFormFieldErrors,
  AdminFormFieldName,
  AdminFormFieldOption,
  AdminFormFieldType,
  AdminFormIntent,
  AdminFormLifecycleState,
  AdminFormProblemKind,
  AdminFormProblemResult,
  AdminFormProblemResultKind,
  AdminFormProps,
  AdminFormRecoveryAction,
  AdminFormRecoveryActionKind,
  AdminFormRenderActionsContext,
  AdminFormRenderFieldContext,
  AdminFormState,
  AdminFormStateOptions,
  AdminFormSubmitAction,
  AdminFormSubmitContext,
  AdminFormSubmitHandler,
  AdminFormSubmitResult,
  AdminFormSubmitSuccess,
  AdminFormValidationFailure,
  AdminMeteringState,
  AdminMutability,
  AdminPanelActionHandler,
  AdminPermissionInspectionInput,
  AdminPermissionInspectionRow,
  AdminPermissionInspectionState,
  AdminPlanSummary,
  AdminProblemReference,
  AdminProviderState,
  AdminStateSource,
  AdminTenantInput,
  AdminTenantSummary,
  AdminTenantSwitchOption,
  AdminTenantSwitchOptionInput,
  AdminUsageMeter,
  BillingEntitlementAdminPanelProps,
  BillingEntitlementAdminPanelReadyState,
  BillingEntitlementAdminPanelState,
  BillingEntitlementAdminPanelStateInput,
  BillingProviderFailureState,
  BillingProviderStatus,
  NonEmptyArray,
  PermissionDeniedAdminPanelState,
  TenantImpersonationConsoleActiveState,
  TenantImpersonationConsoleDeniedState,
  TenantImpersonationConsoleLoadingState,
  TenantImpersonationConsoleProps,
  TenantImpersonationConsoleState,
  TenantImpersonationConsoleStateInput,
  TenantImpersonationConsoleUnavailableState,
} from "./libs/types";
export type {
  AdminDataTableBulkActionEvent,
  AdminDataTableCellContext,
  AdminDataTableColumn,
  AdminDataTableCursorPageInput,
  AdminDataTableEmptyState,
  AdminDataTableField,
  AdminDataTableFilter,
  AdminDataTableFilterChangeEvent,
  AdminDataTableFilterDefinition,
  AdminDataTableFilterOperator,
  AdminDataTableFilterScalar,
  AdminDataTableFilterValue,
  AdminDataTableListConfig,
  AdminDataTableListLoader,
  AdminDataTableListQuery,
  AdminDataTableListResult,
  AdminDataTableListSource,
  AdminDataTableLoadingState,
  AdminDataTableOffsetPageInput,
  AdminDataTablePageChangeEvent,
  AdminDataTablePaginationSummary,
  AdminDataTablePermissionDeniedState,
  AdminDataTableProblemState,
  AdminDataTableProps,
  AdminDataTableReadyState,
  AdminDataTableRecoveryActionEvent,
  AdminDataTableResource,
  AdminDataTableRow,
  AdminDataTableRowActionEvent,
  AdminDataTableRowId,
  AdminDataTableSearchResultInput,
  AdminDataTableSelectionChangeEvent,
  AdminDataTableSort,
  AdminDataTableSortChangeEvent,
  AdminDataTableSortDirection,
  AdminDataTableState,
  AdminDataTableStateBase,
  AdminDataTableStateInput,
} from "./libs/dataTableTypes";
export type {
  TenantBusinessWorkspaceProps,
  TenantWorkspaceActionRequest,
  TenantWorkspaceActionResult,
} from "./libs/TenantBusinessWorkspace";
export type { WebhookReliabilityConsoleProps } from "./libs/WebhookReliabilityConsole";
export type { LifecycleAutomationConsoleProps } from "./libs/LifecycleAutomationConsole";
export type {
  LifecycleAutomationConsoleState,
  LifecycleAutomationEmptyState,
  LifecycleAutomationLoadingState,
  LifecycleAutomationPermissionDeniedState,
  LifecycleAutomationReadyState,
  LifecycleAutomationSource,
  LifecycleAutomationSourceOptions,
  LifecycleDescriptorDiff,
  LifecycleDryRunEvidence,
  LifecycleDryRunFixture,
  LifecycleDryRunFixtureDescriptor,
  LifecycleDryRunRequest,
  LifecycleDryRunResponse,
  LifecycleOperationsProblem,
  LifecycleRuleActionInput,
  LifecycleRuleActionResult,
  LifecycleRuleAdminAction,
  LifecycleRuleOperation,
  LifecycleRunActionEvidence,
  LifecycleRunEvidence,
  LifecycleRunFilters,
  LifecycleRunOperation,
  LifecycleRunOutcome,
  LoadLifecycleAutomationOptions,
} from "./libs/lifecycleAutomation";
