/**
 * @croco/admin-react
 *
 * Provider-neutral React primitives and contracts for SaaS billing, entitlement,
 * quota, usage, and provider status administration.
 */

export {
  AdminActionList,
  BillingEntitlementAdminPanel,
  BillingStatus,
  EntitlementList,
  ImpersonationBanner,
  PlanSummary,
  PermissionInspector,
  ProblemNotice,
  TenantImpersonationConsole,
  TenantSwitcher,
  UsageQuotaMeter,
} from "./libs/components";
export {
  createBillingEntitlementAdminPanelState,
  createCoreProblemDetails,
  createImpersonationExpiredProblemDetails,
  createInMemoryBillingEntitlementAdminPanelState,
  createInMemoryTenantImpersonationConsoleState,
  createPermissionInspectionProblemDetails,
  createPermissionInspectionUnavailableProblemDetails,
  createPermissionDeniedProblemDetails,
  createTenantImpersonationConsoleState,
  createTenantUnavailableProblemDetails,
  evaluateAdminActionPermissions,
} from "./libs/snapshot";
export type {
  AdminActionContract,
  AdminActionPermissionDecision,
  AdminActionSource,
  AdminAuditMetadata,
  AdminBillingStatus,
  AdminEntitlementRow,
  AdminImpersonationActiveInput,
  AdminImpersonationActiveState,
  AdminImpersonationConsoleState,
  AdminImpersonationExpiredInput,
  AdminImpersonationExpiredState,
  AdminImpersonationInactiveInput,
  AdminImpersonationInactiveState,
  AdminImpersonationPrincipal,
  AdminImpersonationStateInput,
  AdminImpersonationUnavailableInput,
  AdminImpersonationUnavailableState,
  AdminMeteringState,
  AdminMutability,
  AdminPanelActionHandler,
  AdminPermissionInspectionInput,
  AdminPermissionInspectionRow,
  AdminPermissionInspectionState,
  AdminPlanSummary,
  AdminProblemReference,
  AdminProviderState,
  AdminStateSource,
  AdminTenantInput,
  AdminTenantSummary,
  AdminTenantSwitchOption,
  AdminTenantSwitchOptionInput,
  AdminUsageMeter,
  BillingEntitlementAdminPanelProps,
  BillingEntitlementAdminPanelReadyState,
  BillingEntitlementAdminPanelState,
  BillingEntitlementAdminPanelStateInput,
  BillingProviderFailureState,
  BillingProviderStatus,
  NonEmptyArray,
  PermissionDeniedAdminPanelState,
  TenantImpersonationConsoleActiveState,
  TenantImpersonationConsoleDeniedState,
  TenantImpersonationConsoleLoadingState,
  TenantImpersonationConsoleProps,
  TenantImpersonationConsoleState,
  TenantImpersonationConsoleStateInput,
  TenantImpersonationConsoleUnavailableState,
} from "./libs/types";
