import type {
  CreateExecutionRecordParams,
  Execution,
  ExecutionContinuationClaim,
  ExecutionContinuationPublication,
  ExecutionError,
  ExecutionLogEntry,
  ExecutionStatus,
  ListExecutionsOptions,
  ListRunningExecutionsOptions,
} from "../types";

/**
 * ExecutionStore defines the storage abstraction for execution records.
 *
 * Implementations (e.g., DrizzleExecutionStore) handle persistence
 * while ExecutionManager uses this abstract class for CRUD operations.
 */
export abstract class ExecutionStore {
  /**
   * Create a new execution record.
   *
   * If idempotencyKey is provided and an existing execution with the same key exists,
   * implementations should return the existing execution instead of creating a new one.
   *
   * @throws Error if creation fails (excluding idempotency conflicts)
   */
  abstract create(params: CreateExecutionRecordParams): Promise<Execution>;

  /**
   * Find an execution by its ID.
   *
   * @returns Execution or null if not found
   */
  abstract findById(id: string): Promise<Execution | null>;

  /**
   * Find an execution by idempotency key.
   *
   * Used for idempotency check during creation.
   *
   * @returns Execution or null if not found
   */
  abstract findByIdempotencyKey(key: string): Promise<Execution | null>;

  /**
   * Update an execution record.
   *
   * Only updates fields provided in the data parameter.
   * Should preserve all existing fields not specified in data.
   * Optional fields provided as undefined should be cleared.
   *
   * @returns Updated execution
   * @throws Error if execution not found or update fails
   */
  abstract update(id: string, data: Partial<Execution>): Promise<Execution>;

  /**
   * Merge one checkpoint key atomically inside the persistence operation.
   *
   * Writes to different keys must not overwrite one another. Concurrent writes to the same key
   * have no invocation-order or Promise-order guarantee: the store serializes the mutations and
   * the mutation applied last wins. Callers that require deterministic same-key ordering or
   * conflict detection must use a separate compare-and-set contract.
   *
   * @throws ExecutionProblem if execution is not found or the merge fails
   */
  abstract mergeCheckpoint(id: string, key: string, value: unknown): Promise<Execution>;

  /**
   * Update an execution only when its persisted status still matches the expected status.
   *
   * This is the required atomic boundary for lifecycle transitions that may race across workers.
   *
   * @returns Updated execution, or null when another actor changed the status first
   */
  abstract updateIfStatus(
    id: string,
    expectedStatus: ExecutionStatus,
    data: Partial<Execution>,
  ): Promise<Execution | null>;

  /**
   * List running executions in stable ID order using keyset pagination.
   */
  abstract listRunning(options: ListRunningExecutionsOptions): Promise<Execution[]>;

  /**
   * List executions with optional filtering.
   *
   * @returns Array of executions matching the criteria
   */
  abstract list(options?: ListExecutionsOptions): Promise<Execution[]>;

  /**
   * Delete an execution record.
   *
   * @throws Error if execution not found or deletion fails
   */
  abstract delete(id: string): Promise<void>;
}

/**
 * Optional store capability for atomic execution log append.
 *
 * Stores that support recordLog should implement this with an atomic append operation,
 * not a read-modify-write replacement of the full logs array.
 */
export interface ExecutionLogStore {
  appendLog(id: string, entry: ExecutionLogEntry): Promise<Execution>;
}

/**
 * Optional store capability for atomically fencing mutations to one execution attempt.
 */
export interface ExecutionAttemptStore {
  updateIfStatusAndAttempt(
    id: string,
    expectedStatus: ExecutionStatus,
    expectedAttempt: number,
    data: Partial<Execution>,
  ): Promise<Execution | null>;
  mergeCheckpointIfStatusAndAttempt(
    id: string,
    expectedStatus: ExecutionStatus,
    expectedAttempt: number,
    key: string,
    value: unknown,
  ): Promise<Execution | null>;
  appendLogIfStatusAndAttempt(
    id: string,
    expectedStatus: ExecutionStatus,
    expectedAttempt: number,
    entry: ExecutionLogEntry,
  ): Promise<Execution | null>;
}

/**
 * Full acquisition input generated by ExecutionManagerImpl.
 */
export interface AcquireExecutionContinuationInput {
  deliveryToken: string;
  workerId: string;
  proposedAttemptToken: string;
  fencingToken: string;
  now: Date;
  leaseDurationMs: number;
  initialToken: string;
}

export type ExecutionContinuationAcquired = {
  execution: Execution;
  claim: ExecutionContinuationClaim;
};

export type AcquireExecutionContinuationResult =
  | ({ kind: "process" } & ExecutionContinuationAcquired)
  | ({
      kind: "publish_pending";
      publication: ExecutionContinuationPublication;
    } & ExecutionContinuationAcquired)
  | {
      kind: "stale";
      execution: Execution;
      deliveryToken: string;
      expectedToken?: string;
    }
  | {
      kind: "contended";
      execution: Execution;
      deliveryToken: string;
      claim: ExecutionContinuationClaim;
    };

export type ClaimedExecutionContinuationUpdate =
  | {
      kind: "renew";
      workerId: string;
      now: Date;
      expiresAt: Date;
    }
  | {
      kind: "stage";
      checkpoints: Record<string, unknown>;
      nextToken: string;
    }
  | { kind: "confirm_publication" }
  | { kind: "complete"; result?: unknown; completedAt: Date }
  | { kind: "fail"; error: ExecutionError; failedAt: Date };

export interface UpdateClaimedExecutionContinuationInput {
  fencingToken: string;
  update: ClaimedExecutionContinuationUpdate;
}

/**
 * Optional store capability for atomic continuation acquisition and fenced mutation.
 *
 * Implementations must perform both operations as compare-and-set writes. A claimed
 * update returns null when the execution is no longer running under the supplied fence.
 */
export interface ExecutionContinuationStore {
  acquireContinuation(
    id: string,
    input: AcquireExecutionContinuationInput,
  ): Promise<AcquireExecutionContinuationResult>;

  updateClaimedContinuation(
    id: string,
    input: UpdateClaimedExecutionContinuationInput,
  ): Promise<Execution | null>;
}
