/**
 * Typed message contracts and explicit, decorator-bound renderer registration for Croco engagement.
 */
export {
  Audience,
  AudienceAlreadyRegisteredProblem,
  AudienceDefinitionInvalidProblem,
  AudienceMetadataMissingProblem,
  AudienceNotRegisteredProblem,
  AudiencePreviewInvalidProblem,
  AudienceRegistry,
  AudienceScopeInvalidProblem,
  CampaignAlreadyRegisteredProblem,
  CampaignDefinitionInvalidProblem,
  CampaignNotRegisteredProblem,
  CampaignRegistry,
  defineCampaign,
  getAudienceDescriptor,
} from "./libs/CampaignContracts";
export type {
  AnyCampaign,
  AudienceBinding,
  AudienceConstructor,
  AudienceContext,
  AudienceDescriptor,
  AudienceOptions,
  AudienceScope,
  AudienceSource,
  CampaignDefinitionInput,
  CampaignDescriptor,
  DefinedCampaign,
} from "./libs/CampaignContracts";
export {
  CampaignDefinitionMismatchProblem,
  CampaignBroadcastService,
  CampaignExecutionInvalidProblem,
  CampaignExecutionNotReadyProblem,
  CampaignExecutionPublisherMissingProblem,
  CampaignSnapshotCreationProblem,
  CampaignSnapshotService,
} from "./libs/CampaignServices";
export type {
  CampaignBroadcastResult,
  CampaignExecutionOptions,
  CampaignExecutionPublication,
  CampaignExecutionPublisher,
  CampaignMessageSender,
  CampaignScheduleOptions,
  CampaignSnapshotCreationResult,
  CampaignSnapshotOptions,
} from "./libs/CampaignServices";
export {
  CampaignSnapshotIncompleteProblem,
  CampaignSnapshotNotFoundProblem,
  CampaignSnapshotPayloadProblem,
  CampaignStoreConflictProblem,
  CampaignStoreValidationProblem,
  InMemoryCampaignStore,
  campaignOutcomeFromSendResult,
  campaignScopeForTenant,
  campaignScopeKey,
  decodeCampaignSnapshotData,
  encodeCampaignSnapshotData,
} from "./libs/CampaignStore";
export type {
  AppendCampaignSnapshotMembersInput,
  CampaignMemberOutcome,
  CampaignMemberOutcomeStatus,
  CampaignProgress,
  CampaignScopeRef,
  CampaignSnapshot,
  CampaignSnapshotMember,
  CampaignSnapshotMemberPage,
  CampaignSnapshotState,
  CampaignSnapshotValue,
  CampaignStore,
  CompleteCampaignSnapshotInput,
  CreateCampaignSnapshotInput,
  FailCampaignSnapshotInput,
  ListCampaignSnapshotMembersOptions,
  RecordCampaignMemberOutcomeInput,
} from "./libs/CampaignStore";
export {
  defineMessage,
  MESSAGE_CHANNELS,
  MessageRendererRegistry,
  Renders,
  getMessageRendererBinding,
  MessageDataInvalidProblem,
  MessageDefinitionInvalidProblem,
  MessageRendererAlreadyRegisteredProblem,
  MessageRendererBindingMismatchProblem,
  MessageRendererChannelMissingProblem,
  MessageRendererMessageMissingProblem,
  MessageRendererMissingProblem,
  MessageRendererUndeclaredChannelProblem,
  MessageAlreadyRegisteredProblem,
} from "./libs/MessageContracts";
export type {
  AnyMessage,
  DefinedMessage,
  EmailContent,
  MessageChannel,
  MessageContent,
  MessageContentByChannel,
  MessageContext,
  MessageData,
  MessageDataInput,
  MessageDefinitionInput,
  MessageDescriptor,
  MessageRenderer,
  MessageRendererBinding,
  MessageRendererConstructor,
  MessageRegistryInspection,
} from "./libs/MessageContracts";
export type { PushContent } from "@croco/notifications-core";
export {
  EngagementCommandInvalidProblem,
  EngagementDispatchFailedProblem,
  EngagementRecordedDispatchFailureProblem,
  EngagementRenderFailedProblem,
  EngagementService,
  EngagementSuppressionEvaluationProblem,
  InMemoryMessageRendererResolver,
  InMemoryRecipientDirectory,
  RecipientDirectoryLookupProblem,
  RecipientDirectoryScopeMismatchProblem,
  RecipientNotFoundProblem,
  RegistryEngagementMessageRenderer,
  createEngagementIdempotencyKey,
} from "./libs/EngagementService";
export type {
  EmailEndpoint,
  EngagementChannelResult,
  EngagementDeliveryPolicy,
  EngagementIdempotencyKeyInput,
  EngagementMessageRenderer,
  EngagementNotificationDispatcher,
  EngagementSendCommand,
  EngagementSendResult,
  EngagementSuppressionContext,
  EngagementSuppressionDecision,
  EngagementSuppressionEvaluator,
  MessageRendererResolver,
  PushEndpoint,
  RecipientDirectory,
  RecipientRef,
  ResolvedRecipient,
} from "./libs/EngagementService";
export {
  ENGAGEMENT_DELIVERY_EVENT_TYPES,
  EngagementPersistenceProblem,
  EngagementStoreValidationProblem,
  assertEngagementPreference,
  assertEngagementStoreText,
  assertEngagementSuppression,
  createEngagementDeliveryEventId,
  createEngagementDispatchId,
  createEngagementDispatchIdentityKey,
  normalizeEngagementEvidence,
  recipientRefForEndpoint,
} from "./libs/EngagementStores";
export type {
  ContactEndpoint,
  ContactEndpointInvalidationResult,
  ContactEndpointStore,
  EmailContactEndpoint,
  EndpointInvalidationReason,
  EngagementDeliveryEvent,
  EngagementDeliveryEventRecordResult,
  EngagementDeliveryEventStore,
  EngagementDeliveryEventType,
  EngagementDispatch,
  EngagementDispatchHistoryCursor,
  EngagementDispatchHistoryPage,
  EngagementDispatchIdentity,
  EngagementDispatchOutcome,
  EngagementDispatchStore,
  EngagementDispatchTarget,
  EngagementEndpointChannel,
  EngagementEvidence,
  EngagementPersistence,
  EngagementPreference,
  EngagementPreferenceLookup,
  EngagementPreferenceScope,
  EngagementPreferenceState,
  EngagementPreferenceStore,
  EngagementStoreTransaction,
  EngagementSuppression,
  EngagementSuppressionLookup,
  InvalidateContactEndpointInput,
  PushContactEndpoint,
  RecordEngagementDeliveryEventInput,
  RecordEngagementDispatchInput,
  SaveContactEndpointInput,
  SuppressionStore,
} from "./libs/EngagementStores";
export { InMemoryEngagementStore } from "./libs/InMemoryEngagementStore";
export {
  EngagementDeliveryEventProcessor,
  EngagementDeliveryEventCorrelationProblem,
  StoreBackedRecipientDirectory,
  StoredEngagementPolicyEvaluator,
} from "./libs/PersistentEngagement";
export type {
  EngagementDeliveryEventProcessingResult,
  StoredEngagementPolicyOptions,
} from "./libs/PersistentEngagement";
export { createEngagementStoreConformanceSuite } from "./libs/EngagementStoreConformance";
export { PushEndpointLifecycle, createPushEndpointId } from "./libs/PushEndpointLifecycle";
export type {
  PushEndpointRegistrationResult,
  PushEndpointScope,
  RegisterPushEndpointInput,
} from "./libs/PushEndpointLifecycle";
export type {
  EngagementStoreConformanceCase,
  EngagementStoreConformanceOptions,
  EngagementStoreConformanceSuite,
} from "./libs/EngagementStoreConformance";
export {
  ContactPolicy,
  ContactPolicyInvalidProblem,
  ContactPolicyConflictProblem,
  ContactPolicyAcceptanceUnknownProblem,
  InMemoryContactPolicyStore,
  assertContactPolicyScope,
  validateContactPolicyConfig,
} from "./libs/ContactPolicy";
export type {
  ContactPolicyScope,
  ContactPolicyTopic,
  ContactPolicyRule,
  ContactPolicyConfig,
  ContactPolicyRequest,
  ContactPolicyDecision,
  ContactPolicyReservation,
  ContactPolicyReserveResult,
  ContactPolicyReconciliation,
  ContactPolicyTransaction,
  ContactPolicyStore,
  ContactPolicyOptions,
  ContactPolicyReservationRef,
  EngagementContactPolicyGate,
} from "./libs/ContactPolicy";
export {
  ReminderInvalidProblem,
  ReminderConflictProblem,
  ReminderAccessDeniedProblem,
  ReminderNotFoundProblem,
  ReminderDispatchProblem,
  assertReminderScope,
  assertReminderInput,
  assertReminderSchedule,
  reminderOccurrenceId,
} from "./libs/ReminderContracts";
export type {
  ReminderScope,
  ReminderSchedule,
  ReminderInput,
  Reminder,
  ReminderOccurrence,
  ReminderMutation,
  ReminderTransaction,
  ReminderStore,
  ReminderActor,
  ReminderAccess,
  ReminderCommand,
  ReminderRevisionCommand,
} from "./libs/ReminderContracts";
export { nextOccurrence } from "./libs/nextOccurrence";
export { createReminderEngagementSender } from "./libs/ReminderEngagement";
export type { ReminderMessageBinding } from "./libs/ReminderEngagement";
export { ReminderService } from "./libs/ReminderService";
export type { ReminderServiceOptions } from "./libs/ReminderService";
export { InMemoryReminderStore } from "./libs/InMemoryReminderStore";
