/**
 * Typed message contracts and explicit, decorator-bound renderer registration for Croco engagement.
 */
export {
  defineMessage,
  MESSAGE_CHANNELS,
  MessageRendererRegistry,
  Renders,
  getMessageRendererBinding,
  MessageDataInvalidProblem,
  MessageDefinitionInvalidProblem,
  MessageRendererAlreadyRegisteredProblem,
  MessageRendererBindingMismatchProblem,
  MessageRendererChannelMissingProblem,
  MessageRendererMessageMissingProblem,
  MessageRendererMissingProblem,
  MessageRendererUndeclaredChannelProblem,
  MessageAlreadyRegisteredProblem,
} from "./libs/MessageContracts";
export type {
  AnyMessage,
  DefinedMessage,
  EmailContent,
  MessageChannel,
  MessageContent,
  MessageContentByChannel,
  MessageContext,
  MessageData,
  MessageDataInput,
  MessageDefinitionInput,
  MessageDescriptor,
  MessageRenderer,
  MessageRendererBinding,
  MessageRendererConstructor,
  MessageRegistryInspection,
} from "./libs/MessageContracts";
export {
  EngagementCommandInvalidProblem,
  EngagementDispatchFailedProblem,
  EngagementRecordedDispatchFailureProblem,
  EngagementRenderFailedProblem,
  EngagementService,
  EngagementSuppressionEvaluationProblem,
  InMemoryMessageRendererResolver,
  InMemoryRecipientDirectory,
  RecipientDirectoryLookupProblem,
  RecipientDirectoryScopeMismatchProblem,
  RecipientNotFoundProblem,
  RegistryEngagementMessageRenderer,
  createEngagementIdempotencyKey,
} from "./libs/EngagementService";
export type {
  EmailEndpoint,
  EngagementChannelResult,
  EngagementDeliveryPolicy,
  EngagementIdempotencyKeyInput,
  EngagementMessageRenderer,
  EngagementNotificationDispatcher,
  EngagementSendCommand,
  EngagementSendResult,
  EngagementSuppressionContext,
  EngagementSuppressionDecision,
  EngagementSuppressionEvaluator,
  MessageRendererResolver,
  PushEndpoint,
  RecipientDirectory,
  RecipientRef,
  ResolvedRecipient,
} from "./libs/EngagementService";
export {
  ENGAGEMENT_DELIVERY_EVENT_TYPES,
  EngagementPersistenceProblem,
  EngagementStoreValidationProblem,
  assertEngagementPreference,
  assertEngagementStoreText,
  assertEngagementSuppression,
  createEngagementDeliveryEventId,
  createEngagementDispatchId,
  createEngagementDispatchIdentityKey,
  normalizeEngagementEvidence,
  recipientRefForEndpoint,
} from "./libs/EngagementStores";
export type {
  ContactEndpoint,
  ContactEndpointInvalidationResult,
  ContactEndpointStore,
  EmailContactEndpoint,
  EndpointInvalidationReason,
  EngagementDeliveryEvent,
  EngagementDeliveryEventRecordResult,
  EngagementDeliveryEventStore,
  EngagementDeliveryEventType,
  EngagementDispatch,
  EngagementDispatchHistoryCursor,
  EngagementDispatchHistoryPage,
  EngagementDispatchIdentity,
  EngagementDispatchOutcome,
  EngagementDispatchStore,
  EngagementDispatchTarget,
  EngagementEndpointChannel,
  EngagementEvidence,
  EngagementPersistence,
  EngagementPreference,
  EngagementPreferenceLookup,
  EngagementPreferenceScope,
  EngagementPreferenceState,
  EngagementPreferenceStore,
  EngagementStoreTransaction,
  EngagementSuppression,
  EngagementSuppressionLookup,
  InvalidateContactEndpointInput,
  PushContactEndpoint,
  RecordEngagementDeliveryEventInput,
  RecordEngagementDispatchInput,
  SaveContactEndpointInput,
  SuppressionStore,
} from "./libs/EngagementStores";
export { InMemoryEngagementStore } from "./libs/InMemoryEngagementStore";
export {
  EngagementDeliveryEventProcessor,
  EngagementDeliveryEventCorrelationProblem,
  StoreBackedRecipientDirectory,
  StoredEngagementPolicyEvaluator,
} from "./libs/PersistentEngagement";
export type {
  EngagementDeliveryEventProcessingResult,
  PushTokenResolver,
  StoredEngagementPolicyOptions,
} from "./libs/PersistentEngagement";
export { createEngagementStoreConformanceSuite } from "./libs/EngagementStoreConformance";
export type {
  EngagementStoreConformanceCase,
  EngagementStoreConformanceOptions,
  EngagementStoreConformanceSuite,
} from "./libs/EngagementStoreConformance";
