/**
 * Typed message contracts and explicit, decorator-bound renderer registration for Croco engagement.
 */
export {
  defineMessage,
  MESSAGE_CHANNELS,
  MessageRendererRegistry,
  Renders,
  getMessageRendererBinding,
  MessageDataInvalidProblem,
  MessageDefinitionInvalidProblem,
  MessageRendererAlreadyRegisteredProblem,
  MessageRendererBindingMismatchProblem,
  MessageRendererChannelMissingProblem,
  MessageRendererMessageMissingProblem,
  MessageRendererMissingProblem,
  MessageRendererUndeclaredChannelProblem,
  MessageAlreadyRegisteredProblem,
} from "./libs/MessageContracts";
export type {
  AnyMessage,
  DefinedMessage,
  EmailContent,
  MessageChannel,
  MessageContent,
  MessageContentByChannel,
  MessageContext,
  MessageData,
  MessageDefinitionInput,
  MessageDescriptor,
  MessageRenderer,
  MessageRendererBinding,
  MessageRendererConstructor,
  MessageRegistryInspection,
} from "./libs/MessageContracts";
export {
  EngagementCommandInvalidProblem,
  EngagementDispatchFailedProblem,
  EngagementRenderFailedProblem,
  EngagementService,
  EngagementSuppressionEvaluationProblem,
  InMemoryMessageRendererResolver,
  InMemoryRecipientDirectory,
  RecipientDirectoryLookupProblem,
  RecipientDirectoryScopeMismatchProblem,
  RecipientNotFoundProblem,
  RegistryEngagementMessageRenderer,
  createEngagementIdempotencyKey,
} from "./libs/EngagementService";
export type {
  EmailEndpoint,
  EngagementChannelResult,
  EngagementDeliveryPolicy,
  EngagementIdempotencyKeyInput,
  EngagementMessageRenderer,
  EngagementNotificationDispatcher,
  EngagementSendCommand,
  EngagementSendResult,
  EngagementSuppressionContext,
  EngagementSuppressionDecision,
  EngagementSuppressionEvaluator,
  MessageRendererResolver,
  PushEndpoint,
  RecipientDirectory,
  RecipientRef,
  ResolvedRecipient,
} from "./libs/EngagementService";
