import { execFileSync, spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

import {
  findBranchProtectionPolicyViolations,
  readExpectedBranchProtectionPolicy,
} from "../branch-protection-policy.mts";
import {
  createProblemCodeRegistry,
  createProblemRegistryArtifacts,
  discoverProblemCodes,
  formatProblemRegistryArtifacts,
  runProblemRegistryCheck,
} from "../problem-registry.mts";
import type { ProblemCodeRegistry } from "../problem-registry.mts";

const tempRepos: string[] = [];

describe("problem-registry.mts", () => {
  afterEach(() => {
    for (const repo of tempRepos.splice(0)) {
      rmSync(repo, { force: true, recursive: true });
    }
  });

  it("discovers Problem codes and writes deterministic registry and cookbook artifacts", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory, ProblemFactory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export function failUpload() {",
        '  throw ProblemFactory.internalServerError("alpha/upload-failed", "failed");',
        "}",
        "export const routeFailure = {",
        '  code: "alpha/invalid-input",',
        "  category: ProblemCategory.ValidationError,",
        "};",
        "",
      ].join("\n"),
    );

    const writeResult = runProblemRegistryCheck(repo, "write");
    const registry = JSON.parse(
      readFileSync(join(repo, "docs/problem-code-registry.json"), "utf-8"),
    );
    const cookbook = readFileSync(
      join(repo, "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md"),
      "utf-8",
    );
    const generatedRegistrySource = readFileSync(
      join(repo, "packages/problems-core/src/generated/problem-code-registry.ts"),
      "utf-8",
    );
    const checkResult = runProblemRegistryCheck(repo, "check");

    expect(writeResult).toEqual(
      expect.objectContaining({
        status: "pass",
        discoveryCount: 3,
        problemCount: 3,
      }),
    );
    expect(registry).toMatchObject({
      version: "croco.problem-code-registry.v1",
      problemCount: 3,
      problems: [
        {
          code: "alpha/invalid-input",
          category: "ValidationError",
          status: 422,
          lifecycle: { status: "active" },
        },
        {
          code: "alpha/not-found",
          category: "NotFound",
          status: 404,
          lifecycle: { status: "active" },
        },
        {
          code: "alpha/upload-failed",
          category: "InternalServerError",
          status: 500,
          lifecycle: { status: "active" },
        },
      ],
    });
    expect(cookbook).toContain("Generated by `pnpm problem-registry:write`");
    expect(cookbook).toContain("## `alpha/not-found`");
    expect(cookbook).toContain("User action:");
    expect(cookbook).toContain("generated client union types");
    expect(generatedRegistrySource).toContain("export type CrocoProblemCode");
    expect(generatedRegistrySource).toContain("export type CrocoProblemDetails");
    expect(checkResult.status).toBe("pass");
  });

  it("publishes cancellation-specific recovery for aborted search operations", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/search-core/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class SearchOperationAbortedProblem extends Problem {",
        "  constructor() {",
        '    super("search-core/operation-aborted", ProblemCategory.BadRequest);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const registry = createProblemCodeRegistry(discoverProblemCodes(repo));

    expect(registry.problems[0]?.recovery).toMatchObject({
      cause: expect.stringContaining("AbortSignal"),
      userAction: expect.stringContaining("new non-aborted AbortSignal"),
      operatorAction: expect.stringContaining("extensions.operation"),
      retryability: "conditional",
    });
  });

  it("publishes non-retryable recovery for canceled Meilisearch tasks", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/search-meilisearch/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class MeilisearchTaskCanceledProblem extends Problem {",
        "  constructor() {",
        '    super("search-meilisearch/task-canceled", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const registry = createProblemCodeRegistry(discoverProblemCodes(repo));

    expect(registry.problems[0]?.recovery).toMatchObject({
      cause: expect.stringContaining("Meilisearch canceled"),
      userAction: expect.stringContaining("Do not retry automatically"),
      operatorAction: expect.stringContaining("extensions.operation"),
      retryability: "not-retryable",
      redactionPolicy: "operator-only",
      telemetry: { severity: "error" },
    });
  });

  it("invalidates stale checks before validating a concurrent generated-state merge candidate", () => {
    const repo = createTempRepo();
    writeProblemFactories(
      repo,
      "packages/base/src/problems.ts",
      Array.from(
        { length: 640 },
        (_, index) => `middle/problem-number-${String(index).padStart(3, "0")}`,
      ),
    );
    expect(writeProblemRegistryFixtureArtifacts(repo)).toEqual(
      expect.objectContaining({ problemCount: 640 }),
    );
    runGit(repo, "init", "--initial-branch=trunk");
    runGit(repo, "config", "user.email", "fixture@croco.dev");
    runGit(repo, "config", "user.name", "Croco fixture");
    commitAll(repo, "base generated state");
    const originalBaseOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "--create", "first-problem");
    writeProblemFactories(repo, "packages/first/src/problems.ts", ["a/first"]);
    const firstRegistry = writeProblemRegistryFixtureArtifacts(repo);
    expect(firstRegistry.problemCount).toBe(641);
    expect(firstRegistry.problems).toHaveLength(641);
    expect(runProblemRegistryCheck(repo, "check", { baseRegistry: null })).toEqual(
      expect.objectContaining({ status: "pass", discoveryCount: 641, problemCount: 641 }),
    );
    commitAll(repo, "first generated state");
    const advancedBaseOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "--create", "second-problem", originalBaseOid);
    writeProblemFactories(repo, "packages/second/src/problems.ts", ["z/second"]);
    const secondRegistry = writeProblemRegistryFixtureArtifacts(repo);
    expect(secondRegistry.problemCount).toBe(641);
    expect(secondRegistry.problems).toHaveLength(641);
    expect(runProblemRegistryCheck(repo, "check", { baseRegistry: null })).toEqual(
      expect.objectContaining({ status: "pass", discoveryCount: 641, problemCount: 641 }),
    );
    commitAll(repo, "second generated state");
    const secondHeadOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "trunk");
    runGit(repo, "merge", "--ff-only", "first-problem");
    expect(runGit(repo, "rev-parse", "HEAD")).toBe(advancedBaseOid);
    expect(originalBaseOid).not.toBe(advancedBaseOid);
    expect(
      findBranchProtectionPolicyViolations({
        branch: "trunk",
        classicProtection: null,
        defaultBranch: "trunk",
        effectiveRules: (
          readExpectedBranchProtectionPolicy().rules as readonly Record<string, unknown>[]
        ).map((rule) => ({ ...structuredClone(rule), ruleset_id: 21_250_891 })),
        rulesets: [
          {
            ...structuredClone(readExpectedBranchProtectionPolicy()),
            id: 21_250_891,
            source_type: "Repository",
          },
        ],
      }),
    ).toEqual([]);

    const merge = spawnSync("git", ["merge", "--no-commit", "--no-ff", secondHeadOid], {
      cwd: repo,
      encoding: "utf-8",
    });
    expect({ status: merge.status, stderr: merge.stderr, stdout: merge.stdout }).toEqual(
      expect.objectContaining({ status: 0 }),
    );
    expect(readRegistry(repo)).toEqual(
      expect.objectContaining({
        problemCount: 641,
        problems: expect.arrayContaining([
          expect.objectContaining({ code: "a/first" }),
          expect.objectContaining({ code: "z/second" }),
        ]),
      }),
    );
    expect(readRegistry(repo).problems).toHaveLength(642);

    const statusBeforeCheck = runGit(repo, "status", "--porcelain=v1");
    const candidateResult = runProblemRegistryCheck(repo, "check", { baseRegistry: null });
    expect(candidateResult).toEqual(
      expect.objectContaining({ status: "fail", discoveryCount: 642, problemCount: 642 }),
    );
    expect(candidateResult.diagnostics).toEqual([
      "docs/problem-code-registry.json drift detected; run pnpm problem-registry:write.",
      "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md drift detected; run pnpm problem-registry:write.",
      "packages/problems-core/src/generated/problem-code-registry.ts drift detected; run pnpm problem-registry:write.",
    ]);
    expect(runGit(repo, "status", "--porcelain=v1")).toBe(statusBeforeCheck);
  }, 30_000);

  it("keeps queued candidates on their exact Problem registry base after trunk advances", () => {
    const repo = createTempRepo();
    writeProblemFactories(repo, "packages/base/src/problems.ts", ["base/original"]);
    writeProblemRegistryFixtureArtifacts(repo);
    runGit(repo, "init", "--initial-branch=trunk");
    runGit(repo, "config", "user.email", "fixture@croco.dev");
    runGit(repo, "config", "user.name", "Croco fixture");
    commitAll(repo, "old base");
    const oldBaseOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "--create", "old-candidate");
    writeProblemFactories(repo, "packages/candidate/src/problems.ts", ["candidate/existing"]);
    writeProblemRegistryFixtureArtifacts(repo);
    commitAll(repo, "old candidate");
    const oldCandidateOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "trunk");
    writeProblemFactories(repo, "packages/new-base/src/problems.ts", ["base/new"]);
    writeProblemRegistryFixtureArtifacts(repo);
    commitAll(repo, "advance trunk");
    const newBaseOid = runGit(repo, "rev-parse", "HEAD");

    runGit(repo, "switch", "--detach", oldCandidateOid);
    expect(runProblemRegistryCheck(repo, "check", { baseRef: oldBaseOid })).toEqual(
      expect.objectContaining({ status: "pass", discoveryCount: 2, problemCount: 2 }),
    );
    expect(runProblemRegistryCheck(repo, "check", { baseRef: "trunk" })).toEqual(
      expect.objectContaining({
        status: "fail",
        diagnostics: expect.arrayContaining([
          expect.stringContaining(
            "Problem code 'base/new' is registered but has no corresponding implementation",
          ),
        ]),
      }),
    );

    runGit(repo, "switch", "--create", "current-candidate", newBaseOid);
    writeProblemFactories(repo, "packages/candidate/src/problems.ts", ["candidate/existing"]);
    writeProblemRegistryFixtureArtifacts(repo);
    expect(runProblemRegistryCheck(repo, "check", { baseRef: newBaseOid })).toEqual(
      expect.objectContaining({ status: "pass", discoveryCount: 3, problemCount: 3 }),
    );

    rmSync(join(repo, "packages/new-base"), { force: true, recursive: true });
    writeProblemRegistryFixtureArtifacts(repo);
    const removal = runProblemRegistryCheck(repo, "check", { baseRef: newBaseOid });
    expect(removal.status).toBe("fail");
    expect(removal.diagnostics).toEqual(
      expect.arrayContaining([
        expect.stringContaining(
          "Problem code 'base/new' is registered but has no corresponding implementation",
        ),
      ]),
    );
  });

  it("publishes runtime-configurable status policy in generated contracts", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/transports-http/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class HttpRequestBodyTooLargeProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/request-body-too-large", ProblemCategory.PayloadTooLarge);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

    const registry = JSON.parse(
      readFileSync(join(repo, "docs/problem-code-registry.json"), "utf-8"),
    );
    const cookbook = readFileSync(
      join(repo, "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md"),
      "utf-8",
    );
    const generatedRegistrySource = readFileSync(
      join(repo, "packages/problems-core/src/generated/problem-code-registry.ts"),
      "utf-8",
    );

    expect(registry.problems[0]).toMatchObject({
      code: "transports-http/request-body-too-large",
      status: 413,
      statusPolicy: {
        kind: "runtime-configurable",
        defaultStatus: 413,
        configuration: "bodyLimitMiddleware.statusCode",
      },
    });
    expect(cookbook).toContain("413\\*");
    expect(cookbook).toContain("Runtime-configurable statuses show their canonical default");
    expect(cookbook).toContain("runtime-configurable via `bodyLimitMiddleware.statusCode`");
    expect(generatedRegistrySource).toContain("CrocoProblemEntryStatus");
    expect(generatedRegistrySource).toContain("? number");
    expect(generatedRegistrySource).toContain(': Entry["status"]');
  });

  it("publishes deterministic recovery metadata for graceful shutdown configuration", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/transports-http/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class GracefulShutdownConfigurationProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/graceful-shutdown-configuration", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "export class HttpRequestBodyTooLargeProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/request-body-too-large", ProblemCategory.PayloadTooLarge);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const registry = readRegistry(repo);
    const problem = registry.problems.find(
      ({ code }) => code === "transports-http/graceful-shutdown-configuration",
    );

    expect(problem?.recovery).toEqual({
      cause: "Graceful shutdown was configured with a non-finite total or event-bus drain timeout.",
      userAction:
        "Ask the operator to correct the graceful shutdown timeout configuration before reconstructing the HTTP application.",
      operatorAction:
        "Set timeoutMs and eventBusDrainTimeoutMs to finite numbers, then reconstruct the middleware or controller before retrying shutdown.",
      retryability: "not-retryable",
      redactionPolicy: "operator-only",
      telemetry: {
        eventName: "croco.problem.error",
        severity: "error",
        attributes: ["problem.code", "problem.category", "problem.status"],
      },
    });
    expect(problem?.recovery.telemetry.attributes).not.toContain("receivedValue");
  });

  it("publishes non-retryable recovery metadata for required LLM metering", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/llm-metering/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class LlmMeteringServiceRequiredProblem extends Problem {",
        "  constructor() {",
        '    super("llm-metering/service-required", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const registry = readRegistry(repo);
    const problem = registry.problems.find(({ code }) => code === "llm-metering/service-required");

    expect(problem?.recovery).toEqual({
      cause:
        "@AiMetered required usage recording, but no scoped or global LlmMeteringService was configured.",
      userAction:
        "Do not retry the unchanged operation; ask the service operator to configure LLM metering or explicitly disable it for an intentionally unmetered method.",
      operatorAction:
        'Bind LlmMeteringService at bootstrap with setLlmMeteringService(), bind it per execution with runWithLlmMeteringService(), or set @AiMetered({ metering: "disabled" }) only when skipping usage recording is intentional.',
      retryability: "not-retryable",
      redactionPolicy: "operator-only",
      telemetry: {
        eventName: "croco.problem.error",
        severity: "error",
        attributes: ["problem.code", "problem.category", "problem.status"],
      },
    });
  });

  it("publishes non-retryable recovery metadata for invalid auth route targets", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/auth-core/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class InvalidRouteMetadataTargetProblem extends Problem {",
        "  constructor() {",
        '    super("auth-core/invalid-route-metadata-target", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const registry = readRegistry(repo);
    const problem = registry.problems.find(
      ({ code }) => code === "auth-core/invalid-route-metadata-target",
    );

    expect(problem?.recovery).toEqual({
      cause:
        "An authentication guard received a route metadata target that was neither an object nor a function.",
      userAction:
        "Do not retry the unchanged request; ask the service operator to correct the route metadata configuration.",
      operatorAction:
        "Inspect the route adapter metadata target and ensure it returns the controller object or constructor before handling requests.",
      retryability: "not-retryable",
      redactionPolicy: "operator-only",
      telemetry: {
        eventName: "croco.problem.error",
        severity: "error",
        attributes: ["problem.code", "problem.category", "problem.status"],
      },
    });
  });

  it("publishes non-retryable recovery metadata for React Email rendering failures", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/notifications-react-email/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class ReactEmailRenderProblem extends Problem {",
        "  constructor() {",
        '    super("notifications-react-email/render-failed", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const registry = readRegistry(repo);
    const problem = registry.problems.find(
      ({ code }) => code === "notifications-react-email/render-failed",
    );

    expect(problem?.recovery).toEqual({
      cause:
        "A React Email component failed while producing deterministic HTML or plain text output.",
      userAction:
        "Do not retry unchanged message data; report the unavailable message so its email component can be corrected.",
      operatorAction:
        "Inspect the component implementation with redacted fixture data, correct the render failure, and redeploy before retrying.",
      retryability: "not-retryable",
      redactionPolicy: "operator-only",
      telemetry: {
        eventName: "croco.problem.error",
        severity: "error",
        attributes: ["problem.code", "problem.category", "problem.status"],
      },
    });
  });

  it("publishes deterministic recovery metadata for graceful shutdown timeout", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/transports-http/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class GracefulShutdownTimeoutProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/graceful-shutdown-timeout", ProblemCategory.InternalServerError);',
        "  }",
        "}",
        "export class HttpRequestBodyTooLargeProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/request-body-too-large", ProblemCategory.PayloadTooLarge);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const registry = readRegistry(repo);
    const problem = registry.problems.find(
      ({ code }) => code === "transports-http/graceful-shutdown-timeout",
    );

    expect(problem?.recovery).toEqual({
      cause:
        "Graceful shutdown did not finish a phase before that phase's configured deadline elapsed.",
      userAction:
        "Wait for the stalled shutdown phase to be investigated before retrying; active requests or cleanup work may still be settling.",
      operatorAction:
        "Inspect the reported phase, timeoutMs, and elapsedMs extensions, then investigate slow request handlers, event-bus draining, or shutdown hooks.",
      retryability: "conditional",
      redactionPolicy: "operator-only",
      telemetry: {
        eventName: "croco.problem.error",
        severity: "error",
        attributes: ["problem.code", "problem.category", "problem.status"],
      },
    });
    expect(problem?.recovery.telemetry.attributes).not.toContain("receivedValue");
  });

  it("fails when a configured status policy no longer resolves to a discovered code", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/transports-http/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class RenamedBodyTooLargeProblem extends Problem {",
        "  constructor() {",
        '    super("transports-http/renamed-body-too-large", ProblemCategory.PayloadTooLarge);',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write")).toEqual(
      expect.objectContaining({
        status: "fail",
        diagnostics: [
          "Status policy references unknown Problem code 'transports-http/request-body-too-large'.",
        ],
      }),
    );
  });

  it("fails check mode when generated artifacts are missing", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "docs/problem-code-registry.json is missing; run pnpm problem-registry:write.",
      "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md is missing; run pnpm problem-registry:write.",
      "packages/problems-core/src/generated/problem-code-registry.ts is missing; run pnpm problem-registry:write.",
    ]);
  });

  it("fails when a duplicate Problem code drifts across categories", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export const routeFailure = {",
        '  code: "shared/problem",',
        "  category: ProblemCategory.InternalServerError,",
        "};",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'shared/problem' has multiple categories: InternalServerError, NotFound.",
    ]);
  });

  it("fails when a duplicate Problem code uses the same category", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export class AlphaAlsoNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing again");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'shared/problem' is declared 2 times: packages/alpha/src/problems.ts:4:5, packages/alpha/src/problems.ts:9:5.",
    ]);
  });

  it("ignores defineRouteProblem metadata projections of Problem classes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        '  readonly code = "alpha/not-found";',
        "  readonly category = ProblemCategory.NotFound;",
        "  constructor() {",
        '    super(undefined, undefined, "missing");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/routes.ts",
      [
        'import { ProblemCategory } from "@croco/problems-core";',
        'import { defineRouteProblem } from "@croco/protocols-rest";',
        'import { AlphaNotFoundProblem } from "./problems";',
        "export const alphaNotFoundRouteProblem = defineRouteProblem(AlphaNotFoundProblem, {",
        '  code: "alpha/not-found",',
        "  category: ProblemCategory.NotFound,",
        '  description: "The requested alpha resource does not exist.",',
        "});",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo)).toEqual([
      expect.objectContaining({
        code: "alpha/not-found",
        sources: [
          expect.objectContaining({
            column: 1,
            file: "packages/alpha/src/problems.ts",
            kind: "problem-class",
            line: 2,
          }),
        ],
      }),
    ]);
  });

  it("keeps defineRouteProblem metadata when no implementation source is visible", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/routes.ts",
      [
        'import { ProblemCategory } from "@croco/problems-core";',
        'import { defineRouteProblem } from "@croco/protocols-rest";',
        "declare class GeneratedAlphaNotFoundProblem {}",
        "export const alphaNotFoundRouteProblem = defineRouteProblem(GeneratedAlphaNotFoundProblem, {",
        '  code: "alpha/generated-not-found",',
        "  category: ProblemCategory.NotFound,",
        '  description: "The generated alpha resource does not exist.",',
        "});",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo)).toEqual([
      expect.objectContaining({
        code: "alpha/generated-not-found",
        sources: [
          expect.objectContaining({
            file: "packages/alpha/src/routes.ts",
            kind: "problem-metadata",
          }),
        ],
      }),
    ]);
  });

  it("discovers class-field, static-code, and local constant Problem codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        'export const ALPHA_CODES = { policy: "alpha/policy" } as const;',
        "export abstract class AlphaProblem extends Problem {}",
        "export class DirectClassFieldProblem extends Problem {",
        '  readonly code = "alpha/class-field";',
        "  readonly category = ProblemCategory.BadRequest;",
        "  constructor() {",
        '    super(undefined, undefined, "class field");',
        "  }",
        "}",
        "export class IndirectClassFieldProblem extends AlphaProblem {",
        "  readonly code = ALPHA_CODES.policy;",
        "  readonly category = ProblemCategory.Forbidden;",
        "  constructor() {",
        '    super(undefined, undefined, "policy");',
        "  }",
        "}",
        "export class StaticCodeProblem extends Problem {",
        '  static readonly CODE = "alpha/static-code";',
        "  constructor() {",
        '    super(StaticCodeProblem.CODE, ProblemCategory.InternalServerError, "static");',
        "  }",
        "}",
        "export class DefaultCodeProblem extends Problem {",
        '  constructor(code = "alpha/default-code") {',
        '    super(code, ProblemCategory.Conflict, "default");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/class-field",
      "alpha/default-code",
      "alpha/policy",
      "alpha/static-code",
    ]);
  });

  it("discovers relative imported constant Problem codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/codes.ts",
      [
        "export const PROBLEM_CODES = {",
        '  direct: "alpha/imported-direct",',
        '  aliased: "alpha/imported-aliased",',
        '  metadata: "alpha/imported-metadata",',
        "} as const;",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        'import { PROBLEM_CODES as CODES } from "./codes.js";',
        "export class ImportedDirectProblem extends Problem {",
        "  constructor() {",
        '    super(CODES.direct, ProblemCategory.BadRequest, "direct");',
        "  }",
        "}",
        "export class ImportedAliasedProblem extends Problem {",
        "  readonly code = CODES.aliased;",
        "  readonly category = ProblemCategory.Forbidden;",
        "  constructor() {",
        '    super(undefined, undefined, "aliased");',
        "  }",
        "}",
        "export const importedMetadata = {",
        "  code: CODES.metadata,",
        "  category: ProblemCategory.Conflict,",
        "} as const;",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/imported-aliased",
      "alpha/imported-direct",
      "alpha/imported-metadata",
    ]);
  });

  it("discovers enum-backed Problem wrapper factory codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/execution/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export enum ExecutionProblemCode {",
        '  NOT_FOUND = "execution/not-found",',
        '  CONFLICT = "execution/conflict",',
        '  MAX_RETRIES_EXCEEDED = "execution/max-retries-exceeded",',
        '  INVALID_STATE_TRANSITION = "execution/invalid-state-transition",',
        "}",
        "export class ExecutionProblem extends Problem {",
        "  constructor(code: ExecutionProblemCode, category: ProblemCategory, detail?: string) {",
        "    super(code, category, detail);",
        "  }",
        "}",
        "export class ExecutionProblems {",
        "  static notFound(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.NOT_FOUND, ProblemCategory.NotFound, detail);",
        "  }",
        "  static conflict(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.CONFLICT, ProblemCategory.Conflict, detail);",
        "  }",
        "  static maxRetriesExceeded(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.MAX_RETRIES_EXCEEDED, ProblemCategory.Conflict, detail);",
        "  }",
        "  static invalidStateTransition(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.INVALID_STATE_TRANSITION, ProblemCategory.Conflict, detail);",
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "execution/conflict",
      "execution/invalid-state-transition",
      "execution/max-retries-exceeded",
      "execution/not-found",
    ]);
  });

  it("ignores tests while discovering public package source codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/tests/problems.spec.ts",
      [
        'import { ProblemFactory } from "@croco/problems-core";',
        'ProblemFactory.badRequest("fixture/test-only");',
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/problems.mts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaConflictProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/conflict", ProblemCategory.Conflict, "conflict");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/tests/problems.spec.mts",
      [
        'import { ProblemFactory } from "@croco/problems-core";',
        'ProblemFactory.badRequest("fixture/mts-test-only");',
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/conflict",
      "alpha/not-found",
    ]);
  });

  it("fails when an active registry entry no longer has an implementation", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaRemovedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/removed", ProblemCategory.NotFound, "removed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

    writeFile(repo, "packages/alpha/src/problems.ts", "");

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'alpha/removed' is registered but has no corresponding implementation; mark it deprecated with migration metadata before removing the source.",
    ]);
  });

  it("preserves explicitly deprecated registry entries after their implementation is removed", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaKeptProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/kept", ProblemCategory.NotFound, "kept");',
        "  }",
        "}",
        "export class AlphaRemovedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/removed", ProblemCategory.NotFound, "removed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaKeptProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/kept", ProblemCategory.NotFound, "kept");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    const registry = readRegistry(repo);
    writeRegistry(repo, {
      ...registry,
      problems: registry.problems.map((problem) =>
        problem.code === "alpha/removed"
          ? {
              ...problem,
              lifecycle: {
                status: "deprecated",
                deprecation: {
                  reason: "The code was replaced by alpha/kept.",
                  migrationNote: "Branch clients on alpha/kept before removing alpha/removed.",
                  replacementCode: "alpha/kept",
                },
              },
              sources: [],
            }
          : problem,
      ),
    });

    const writeResult = runProblemRegistryCheck(repo, "write");
    const checkResult = runProblemRegistryCheck(repo, "check");
    const updatedRegistry = readRegistry(repo);

    expect(writeResult.status).toBe("pass");
    expect(checkResult.status).toBe("pass");
    expect(
      updatedRegistry.problems.find((problem) => problem.code === "alpha/removed"),
    ).toMatchObject({
      lifecycle: { status: "deprecated" },
      sources: [],
    });
  });

  it("preserves deprecated registry entries without replacements when a no-replacement reason is present", () => {
    const repo = setupDeprecatedAlphaRemovedRegistry({
      reason: "The upstream capability was removed.",
      migrationNote: "Stop branching on alpha/removed in generated clients.",
      noReplacementReason: "The retired capability has no supported equivalent.",
    });

    const writeResult = runProblemRegistryCheck(repo, "write");
    const cookbook = readFileSync(
      join(repo, "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md"),
      "utf-8",
    );

    expect(writeResult.status).toBe("pass");
    expect(runProblemRegistryCheck(repo, "check").status).toBe("pass");
    expect(cookbook).toContain(
      "- No replacement reason: The retired capability has no supported equivalent.",
    );
  });

  it("rejects deprecated lifecycle metadata without replacement guidance", () => {
    const repo = setupDeprecatedAlphaRemovedRegistry({
      reason: "The code was retired.",
      migrationNote: "Stop branching on alpha/removed.",
    });

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Deprecated Problem code 'alpha/removed' must declare replacementCode or noReplacementReason.",
    ]);
  });

  it("rejects deprecated replacement codes that are self-references, unknown, or deprecated", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        'export class AlphaSelfProblem extends Problem { constructor() { super("alpha/self", ProblemCategory.Gone, "self"); } }',
        'export class AlphaUnknownProblem extends Problem { constructor() { super("alpha/unknown", ProblemCategory.Gone, "unknown"); } }',
        'export class AlphaOldTargetProblem extends Problem { constructor() { super("alpha/old-target", ProblemCategory.Gone, "old"); } }',
        'export class AlphaDeprecatedTargetProblem extends Problem { constructor() { super("alpha/deprecated-target", ProblemCategory.Gone, "target"); } }',
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

    const registry = readRegistry(repo);
    writeRegistry(repo, {
      ...registry,
      problems: registry.problems.map((problem) => {
        const deprecation = {
          reason: "The code was retired.",
          migrationNote: "Follow the replacement guidance before removing branches.",
        };

        if (problem.code === "alpha/self") {
          return {
            ...problem,
            lifecycle: {
              status: "deprecated",
              deprecation: { ...deprecation, replacementCode: "alpha/self" },
            },
          };
        }

        if (problem.code === "alpha/unknown") {
          return {
            ...problem,
            lifecycle: {
              status: "deprecated",
              deprecation: { ...deprecation, replacementCode: "alpha/missing" },
            },
          };
        }

        if (problem.code === "alpha/old-target") {
          return {
            ...problem,
            lifecycle: {
              status: "deprecated",
              deprecation: { ...deprecation, replacementCode: "alpha/deprecated-target" },
            },
          };
        }

        if (problem.code === "alpha/deprecated-target") {
          return {
            ...problem,
            lifecycle: {
              status: "deprecated",
              deprecation: {
                ...deprecation,
                noReplacementReason: "The deprecated target has no active equivalent.",
              },
            },
          };
        }

        return problem;
      }),
    });

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Deprecated Problem code 'alpha/old-target' replacementCode 'alpha/deprecated-target' points to a deprecated Problem code.",
      "Deprecated Problem code 'alpha/self' replacementCode must reference a different Problem code.",
      "Deprecated Problem code 'alpha/unknown' replacementCode 'alpha/missing' is not registered.",
    ]);
  });

  it("requires changeset or migration evidence for category, status, or retryability changes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaChangedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/changed", ProblemCategory.NotFound, "changed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaChangedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/changed", ProblemCategory.Conflict, "changed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const blockedResult = runProblemRegistryCheck(repo, "write");
    expect(blockedResult.status).toBe("fail");
    expect(blockedResult.diagnostics).toEqual([
      "Problem code 'alpha/changed' changed category NotFound -> Conflict, status 404 -> 409, retryability not-retryable -> conditional without an explicit changeset or migration note mentioning that code.",
    ]);

    writeFile(
      repo,
      ".changeset/alpha-problem-change.md",
      [
        "---",
        '"@croco/alpha": patch',
        "---",
        "",
        "Document the `alpha/changed` Problem code migration from 404 to 409 handling.",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    expect(runProblemRegistryCheck(repo, "check").status).toBe("pass");
  });

  it("compares committed registry artifacts against the base registry for contract changes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaChangedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/changed", ProblemCategory.NotFound, "changed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const baseRegistry = readRegistry(repo);

    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaChangedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/changed", ProblemCategory.Conflict, "changed");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    writeRegistry(repo, {
      ...baseRegistry,
      problems: baseRegistry.problems.map((problem) =>
        problem.code === "alpha/changed"
          ? {
              ...problem,
              category: "Conflict",
              status: 409,
              title: "Conflict",
              recovery: {
                ...problem.recovery,
                retryability: "conditional",
              },
            }
          : problem,
      ),
    });

    const result = runProblemRegistryCheck(repo, "check", { baseRegistry });

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'alpha/changed' changed category NotFound -> Conflict, status 404 -> 409, retryability not-retryable -> conditional without an explicit changeset or migration note mentioning that code.",
    ]);
  });

  it("requires changeset or migration evidence for lifecycle deprecation changes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaChangedProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/changed", ProblemCategory.Gone, "changed");',
        "  }",
        "}",
        "export class AlphaReplacementProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/replacement", ProblemCategory.Gone, "replacement");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");
    const baseRegistry = readRegistry(repo);
    writeRegistry(repo, {
      ...baseRegistry,
      problems: baseRegistry.problems.map((problem) =>
        problem.code === "alpha/changed"
          ? {
              ...problem,
              lifecycle: {
                status: "deprecated",
                deprecation: {
                  reason: "The code was replaced.",
                  migrationNote: "Branch clients on alpha/replacement.",
                  replacementCode: "alpha/replacement",
                },
              },
            }
          : problem,
      ),
    });

    const blockedResult = runProblemRegistryCheck(repo, "check", { baseRegistry });
    expect(blockedResult.status).toBe("fail");
    expect(blockedResult.diagnostics).toEqual([
      "Problem code 'alpha/changed' changed lifecycle active -> deprecated, deprecation.reason (none) -> The code was replaced., deprecation.migrationNote (none) -> Branch clients on alpha/replacement., deprecation.replacementCode (none) -> alpha/replacement without an explicit changeset or migration note mentioning that code.",
    ]);

    writeFile(
      repo,
      "docs/release/problem-code-migrations.md",
      [
        "# Problem code migrations",
        "",
        "- `alpha/changed` is deprecated in favor of `alpha/replacement`.",
        "",
      ].join("\n"),
    );

    expect(runProblemRegistryCheck(repo, "write", { baseRegistry }).status).toBe("pass");
    expect(runProblemRegistryCheck(repo, "check", { baseRegistry }).status).toBe("pass");
  });

  it("rejects unsafe Problem extension redaction fixtures", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { ProblemFactory } from "@croco/problems-core";',
        "export function failProvider() {",
        '  return ProblemFactory.internalServerError("alpha/upstream", "failed", {',
        "    extensions: {",
        "      rawProviderResponse: { status: 500 },",
        '      message: "Bearer sk_live_secret",',
        "    },",
        "  });",
        "}",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Unsafe Problem extension 'rawProviderResponse' at packages/alpha/src/problems.ts:5:7: raw request/provider payloads must be summarized and redacted before they enter Problem extensions.",
      "Unsafe Problem extension 'message' at packages/alpha/src/problems.ts:6:16: literal secret-looking values must be redacted before they enter Problem extensions.",
    ]);
  });
});

function createTempRepo(): string {
  const repo = mkdtempSync(join(tmpdir(), "croco-problem-registry-"));
  tempRepos.push(repo);
  return repo;
}

function writeFile(repo: string, path: string, content: string): void {
  const absolutePath = join(repo, path);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content);
}

function writeProblemFactories(repo: string, path: string, codes: readonly string[]): void {
  writeFile(
    repo,
    path,
    [
      'import { ProblemFactory } from "@croco/problems-core";',
      ...codes.map(
        (code, index) =>
          `export function problem${index}() { return ProblemFactory.badRequest("${code}"); }`,
      ),
      "",
    ].join("\n"),
  );
}

function writeProblemRegistryFixtureArtifacts(repo: string): ProblemCodeRegistry {
  const registry = createProblemCodeRegistry(discoverProblemCodes(repo));

  for (const [path, content] of formatProblemRegistryArtifacts(
    createProblemRegistryArtifacts(registry),
  )) {
    writeFile(repo, path, content);
  }

  return registry;
}

function runGit(repo: string, ...arguments_: readonly string[]): string {
  return execFileSync("git", arguments_, { cwd: repo, encoding: "utf-8" }).trim();
}

function commitAll(repo: string, message: string): void {
  runGit(repo, "add", ".");
  runGit(repo, "commit", "--message", message);
}

function setupDeprecatedAlphaRemovedRegistry(deprecation: Record<string, unknown>): string {
  const repo = createTempRepo();
  writeFile(
    repo,
    "packages/alpha/src/problems.ts",
    [
      'import { Problem, ProblemCategory } from "@croco/problems-core";',
      "export class AlphaRemovedProblem extends Problem {",
      "  constructor() {",
      '    super("alpha/removed", ProblemCategory.Gone, "removed");',
      "  }",
      "}",
      "",
    ].join("\n"),
  );
  expect(runProblemRegistryCheck(repo, "write").status).toBe("pass");

  writeFile(repo, "packages/alpha/src/problems.ts", "");
  const registry = readRegistry(repo);
  const deprecatedLifecycle = JSON.parse(
    JSON.stringify({ status: "deprecated", deprecation }),
  ) as ProblemCodeRegistry["problems"][number]["lifecycle"];

  writeRegistry(repo, {
    ...registry,
    problems: registry.problems.map((problem) =>
      problem.code === "alpha/removed"
        ? {
            ...problem,
            lifecycle: deprecatedLifecycle,
            sources: [],
          }
        : problem,
    ),
  });

  return repo;
}

function readRegistry(repo: string): ProblemCodeRegistry {
  return JSON.parse(readFileSync(join(repo, "docs/problem-code-registry.json"), "utf-8"));
}

function writeRegistry(repo: string, registry: ProblemCodeRegistry): void {
  writeFile(repo, "docs/problem-code-registry.json", `${JSON.stringify(registry, null, 2)}\n`);
}
