import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";

import { discoverProblemCodes, runProblemRegistryCheck } from "../problem-registry.mts";

const tempRepos: string[] = [];

describe("problem-registry.mts", () => {
  afterEach(() => {
    for (const repo of tempRepos.splice(0)) {
      rmSync(repo, { force: true, recursive: true });
    }
  });

  it("discovers Problem codes and writes deterministic registry and cookbook artifacts", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory, ProblemFactory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export function failUpload() {",
        '  throw ProblemFactory.internalServerError("alpha/upload-failed", "failed");',
        "}",
        "export const routeFailure = {",
        '  code: "alpha/invalid-input",',
        "  category: ProblemCategory.ValidationError,",
        "};",
        "",
      ].join("\n"),
    );

    const writeResult = runProblemRegistryCheck(repo, "write");
    const registry = JSON.parse(
      readFileSync(join(repo, "docs/problem-code-registry.json"), "utf-8"),
    );
    const cookbook = readFileSync(
      join(repo, "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md"),
      "utf-8",
    );
    const checkResult = runProblemRegistryCheck(repo, "check");

    expect(writeResult).toEqual(
      expect.objectContaining({
        status: "pass",
        discoveryCount: 3,
        problemCount: 3,
      }),
    );
    expect(registry).toMatchObject({
      version: "croco.problem-code-registry.v1",
      problemCount: 3,
      problems: [
        { code: "alpha/invalid-input", category: "ValidationError", status: 422 },
        { code: "alpha/not-found", category: "NotFound", status: 404 },
        { code: "alpha/upload-failed", category: "InternalServerError", status: 500 },
      ],
    });
    expect(cookbook).toContain("Generated by `pnpm problem-registry:write`");
    expect(cookbook).toContain("## `alpha/not-found`");
    expect(cookbook).toContain("User action:");
    expect(checkResult.status).toBe("pass");
  });

  it("fails check mode when generated artifacts are missing", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "docs/problem-code-registry.json is missing; run pnpm problem-registry:write.",
      "packages/docs/src/content/docs/en/reference/problem-recovery-cookbook.md is missing; run pnpm problem-registry:write.",
    ]);
  });

  it("fails when a duplicate Problem code drifts across categories", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export const routeFailure = {",
        '  code: "shared/problem",',
        "  category: ProblemCategory.InternalServerError,",
        "};",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'shared/problem' has multiple categories: InternalServerError, NotFound.",
    ]);
  });

  it("fails when a duplicate Problem code uses the same category", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "export class AlphaAlsoNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("shared/problem", ProblemCategory.NotFound, "missing again");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    const result = runProblemRegistryCheck(repo, "check");

    expect(result.status).toBe("fail");
    expect(result.diagnostics).toEqual([
      "Problem code 'shared/problem' is declared 2 times: packages/alpha/src/problems.ts:4:5, packages/alpha/src/problems.ts:9:5.",
    ]);
  });

  it("discovers class-field, static-code, and local constant Problem codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        'export const ALPHA_CODES = { policy: "alpha/policy" } as const;',
        "export abstract class AlphaProblem extends Problem {}",
        "export class DirectClassFieldProblem extends Problem {",
        '  readonly code = "alpha/class-field";',
        "  readonly category = ProblemCategory.BadRequest;",
        "  constructor() {",
        '    super(undefined, undefined, "class field");',
        "  }",
        "}",
        "export class IndirectClassFieldProblem extends AlphaProblem {",
        "  readonly code = ALPHA_CODES.policy;",
        "  readonly category = ProblemCategory.Forbidden;",
        "  constructor() {",
        '    super(undefined, undefined, "policy");',
        "  }",
        "}",
        "export class StaticCodeProblem extends Problem {",
        '  static readonly CODE = "alpha/static-code";',
        "  constructor() {",
        '    super(StaticCodeProblem.CODE, ProblemCategory.InternalServerError, "static");',
        "  }",
        "}",
        "export class DefaultCodeProblem extends Problem {",
        '  constructor(code = "alpha/default-code") {',
        '    super(code, ProblemCategory.Conflict, "default");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/class-field",
      "alpha/default-code",
      "alpha/policy",
      "alpha/static-code",
    ]);
  });

  it("discovers relative imported constant Problem codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/codes.ts",
      [
        "export const PROBLEM_CODES = {",
        '  direct: "alpha/imported-direct",',
        '  aliased: "alpha/imported-aliased",',
        '  metadata: "alpha/imported-metadata",',
        "} as const;",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        'import { PROBLEM_CODES as CODES } from "./codes.js";',
        "export class ImportedDirectProblem extends Problem {",
        "  constructor() {",
        '    super(CODES.direct, ProblemCategory.BadRequest, "direct");',
        "  }",
        "}",
        "export class ImportedAliasedProblem extends Problem {",
        "  readonly code = CODES.aliased;",
        "  readonly category = ProblemCategory.Forbidden;",
        "  constructor() {",
        '    super(undefined, undefined, "aliased");',
        "  }",
        "}",
        "export const importedMetadata = {",
        "  code: CODES.metadata,",
        "  category: ProblemCategory.Conflict,",
        "} as const;",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/imported-aliased",
      "alpha/imported-direct",
      "alpha/imported-metadata",
    ]);
  });

  it("discovers enum-backed Problem wrapper factory codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/execution/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export enum ExecutionProblemCode {",
        '  NOT_FOUND = "execution/not-found",',
        '  CONFLICT = "execution/conflict",',
        '  MAX_RETRIES_EXCEEDED = "execution/max-retries-exceeded",',
        '  INVALID_STATE_TRANSITION = "execution/invalid-state-transition",',
        "}",
        "export class ExecutionProblem extends Problem {",
        "  constructor(code: ExecutionProblemCode, category: ProblemCategory, detail?: string) {",
        "    super(code, category, detail);",
        "  }",
        "}",
        "export class ExecutionProblems {",
        "  static notFound(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.NOT_FOUND, ProblemCategory.NotFound, detail);",
        "  }",
        "  static conflict(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.CONFLICT, ProblemCategory.Conflict, detail);",
        "  }",
        "  static maxRetriesExceeded(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.MAX_RETRIES_EXCEEDED, ProblemCategory.Conflict, detail);",
        "  }",
        "  static invalidStateTransition(detail: string): ExecutionProblem {",
        "    return new ExecutionProblem(ExecutionProblemCode.INVALID_STATE_TRANSITION, ProblemCategory.Conflict, detail);",
        "  }",
        "}",
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "execution/conflict",
      "execution/invalid-state-transition",
      "execution/max-retries-exceeded",
      "execution/not-found",
    ]);
  });

  it("ignores tests while discovering public package source codes", () => {
    const repo = createTempRepo();
    writeFile(
      repo,
      "packages/alpha/src/problems.ts",
      [
        'import { Problem, ProblemCategory } from "@croco/problems-core";',
        "export class AlphaNotFoundProblem extends Problem {",
        "  constructor() {",
        '    super("alpha/not-found", ProblemCategory.NotFound, "missing");',
        "  }",
        "}",
        "",
      ].join("\n"),
    );
    writeFile(
      repo,
      "packages/alpha/src/tests/problems.spec.ts",
      [
        'import { ProblemFactory } from "@croco/problems-core";',
        'ProblemFactory.badRequest("fixture/test-only");',
        "",
      ].join("\n"),
    );

    expect(discoverProblemCodes(repo).map((discovery) => discovery.code)).toEqual([
      "alpha/not-found",
    ]);
  });
});

function createTempRepo(): string {
  const repo = mkdtempSync(join(tmpdir(), "croco-problem-registry-"));
  tempRepos.push(repo);
  return repo;
}

function writeFile(repo: string, path: string, content: string): void {
  const absolutePath = join(repo, path);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content);
}
