export { DesktopDefinitionProblem } from "./libs/DesktopDefinitionProblem";
export { desktop } from "./libs/desktop";
export type { DesktopDefinitionProblemCode } from "./libs/DesktopDefinitionProblem";
export type {
  AnyDesktopCommand,
  AnyDesktopContract,
  AnyDesktopEvent,
  AnyDesktopWindow,
  BoundDesktopCommand,
  BoundDesktopContract,
  BoundDesktopContracts,
  BoundDesktopEvent,
  BoundDesktopWindows,
  DesktopAppContractMetadata,
  DesktopAppDefinition,
  DesktopAppMetadata,
  DesktopAppOptions,
  DesktopCommandDefinition,
  DesktopCommandKind,
  DesktopCommandRecord,
  DesktopContractDefinition,
  DesktopContractRecord,
  DesktopContractMemberMetadata,
  DesktopContractMetadata,
  DesktopContractOptions,
  DesktopEventDefinition,
  DesktopEventOptions,
  DesktopEventRecord,
  DesktopLocalWindowDefinition,
  DesktopLocalWindowMetadata,
  DesktopLocalWindowOptions,
  DesktopMemberReferenceMetadata,
  DesktopMutationDefinition,
  DesktopMutationOptions,
  DesktopQueryDefinition,
  DesktopQueryOptions,
  DesktopRemoteWindowDefinition,
  DesktopRemoteWindowMetadata,
  DesktopRemoteWindowOptions,
  DesktopWindowRecord,
  InferDesktopAppContracts,
  InferDesktopAppWindows,
  InferDesktopCommandInput,
  InferDesktopCommandOutput,
  InferDesktopContractCommands,
  InferDesktopContractEvents,
  InferDesktopEventPayload,
  InferDesktopSchema,
  KeyedDesktopCommand,
  KeyedDesktopEvent,
  ReservedDesktopKey,
} from "./libs/types";
