export { DesktopDefinitionProblem } from "./libs/DesktopDefinitionProblem";
export {
  compileDesktopWireSchema,
  DesktopWireSchemaProblem,
  formatDesktopWireSchemaDiagnostic,
  parseDesktopWireValue,
  stringifyDesktopWireSchemaDescriptor,
} from "./libs/DesktopWireSchema";
export { desktop } from "./libs/desktop";
export type { DesktopDefinitionProblemCode } from "./libs/DesktopDefinitionProblem";
export type {
  DesktopWireEnumDescriptor,
  DesktopWireLiteralDescriptor,
  DesktopWireObjectDescriptor,
  DesktopWirePrimitiveDescriptor,
  DesktopWireSchemaContext,
  DesktopWireSchemaDescriptor,
  DesktopWireSchemaDiagnostic,
  DesktopWireSchemaDiagnosticCode,
  DesktopWireSourceLocation,
} from "./libs/DesktopWireSchema";
export type {
  AnyDesktopCommand,
  AnyDesktopContract,
  AnyDesktopEvent,
  AnyDesktopWindow,
  BoundDesktopCommand,
  BoundDesktopContract,
  BoundDesktopContracts,
  BoundDesktopEvent,
  BoundDesktopWindows,
  DesktopAppContractMetadata,
  DesktopAppDefinition,
  DesktopAppImplementation,
  DesktopAppImplementer,
  DesktopAppMetadata,
  DesktopAppOptions,
  DesktopCommandDefinition,
  DesktopCommandHandler,
  DesktopCommandKind,
  DesktopCommandRecord,
  DesktopContractDefinition,
  DesktopContractImplementation,
  DesktopContractRecord,
  DesktopContractMemberMetadata,
  DesktopContractMetadata,
  DesktopContractOptions,
  DesktopEventDefinition,
  DesktopEventOptions,
  DesktopEventRecord,
  DesktopLocalWindowDefinition,
  DesktopLocalWindowMetadata,
  DesktopLocalWindowOptions,
  DesktopMemberReferenceMetadata,
  DesktopMutationDefinition,
  DesktopMutationOptions,
  DesktopQueryDefinition,
  DesktopQueryOptions,
  DesktopRemoteWindowDefinition,
  DesktopRemoteWindowMetadata,
  DesktopRemoteWindowOptions,
  DesktopWindowRecord,
  InferDesktopAppContracts,
  InferDesktopAppWindows,
  InferDesktopCommandInput,
  InferDesktopCommandOutput,
  InferDesktopContractCommands,
  InferDesktopContractEvents,
  InferDesktopEventPayload,
  InferDesktopSchema,
  KeyedDesktopCommand,
  KeyedDesktopEvent,
  ReservedDesktopKey,
} from "./libs/types";
