#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const CONTRACT_COUNT = 20;
const COMMANDS_PER_CONTRACT = 10;
const fixturePath = join(import.meta.dirname, "large-app.ts");

export function largeFixtureSource(): string {
  const contracts = Array.from({ length: CONTRACT_COUNT }, (_, contractIndex) => {
    const contractNumber = contractIndex + 1;
    const commands = Array.from({ length: COMMANDS_PER_CONTRACT }, (_, commandIndex) => {
      const commandNumber = contractIndex * COMMANDS_PER_CONTRACT + commandIndex + 1;
      const constructor = commandNumber % 2 === 0 ? "mutation" : "query";
      return [
        `    command${digits(commandNumber, 3)}: desktop.${constructor}({`,
        "      input: z.object({ value: z.string() }),",
        "      output: z.object({ result: z.string() }),",
        "    }),",
      ].join("\n");
    });
    return [
      `const contract${digits(contractNumber, 2)} = desktop.contract({`,
      "  commands: {",
      ...commands,
      "  },",
      "});",
    ].join("\n");
  });

  const contractEntries = Array.from(
    { length: CONTRACT_COUNT },
    (_, index) => `    contract${digits(index + 1, 2)},`,
  );
  const windows = Array.from({ length: CONTRACT_COUNT }, (_, contractIndex) => {
    const contractNumber = contractIndex + 1;
    const commandReferences = Array.from({ length: COMMANDS_PER_CONTRACT }, (_, commandIndex) => {
      const commandNumber = contractIndex * COMMANDS_PER_CONTRACT + commandIndex + 1;
      return `        contract${digits(contractNumber, 2)}.commands.command${digits(commandNumber, 3)},`;
    });
    return [
      `    window${digits(contractNumber, 2)}: desktop.window.local({`,
      "      expose: [",
      ...commandReferences,
      "      ],",
      "    }),",
    ].join("\n");
  });
  const implementations = Array.from({ length: CONTRACT_COUNT }, (_, contractIndex) => {
    const contractNumber = contractIndex + 1;
    const handlers = Array.from({ length: COMMANDS_PER_CONTRACT }, (_, commandIndex) => {
      const commandNumber = contractIndex * COMMANDS_PER_CONTRACT + commandIndex + 1;
      return `        command${digits(commandNumber, 3)}: (input, context) => context.ok({ result: input.value }),`;
    });
    return [
      `    contract${digits(contractNumber, 2)}: {`,
      "      commands: {",
      ...handlers,
      "      },",
      "    },",
    ].join("\n");
  });
  const expectedContractKeys = Array.from(
    { length: CONTRACT_COUNT },
    (_, index) => `  | "contract${digits(index + 1, 2)}"${index === CONTRACT_COUNT - 1 ? ";" : ""}`,
  );

  return [
    "// Generated by generate-large-fixture.mts. Do not edit by hand.",
    'import { z } from "zod";',
    "",
    'import { desktop } from "../src/libs/desktop";',
    'import type { DesktopAppImplementation } from "../src/libs/types";',
    "",
    "type Equal<TLeft, TRight> =",
    "  (<T>() => T extends TLeft ? 1 : 2) extends <T>() => T extends TRight ? 1 : 2 ? true : false;",
    "type Assert<TValue extends true> = TValue;",
    "",
    ...contracts.flatMap((contract) => [contract, ""]),
    "const largeApp = desktop.app({",
    "  contracts: {",
    ...contractEntries,
    "  },",
    "  windows: {",
    ...windows,
    "  },",
    "});",
    "",
    "const implementation: DesktopAppImplementation<typeof largeApp.contracts> = {",
    "  contracts: {",
    ...implementations,
    "  },",
    "};",
    "",
    "largeApp.implement(implementation);",
    "",
    "type ExpectedContractKey =",
    ...expectedContractKeys,
    "type ContractKeyCompletion = Assert<Equal<keyof typeof largeApp.contracts, ExpectedContractKey>>;",
    "type LastHandlerInput = Parameters<",
    "  typeof implementation.contracts.contract20.commands.command200",
    ">[0];",
    "type HandlerInference = Assert<Equal<LastHandlerInput, { value: string }>>;",
    "",
    "export type LargeFixtureAssertions = ContractKeyCompletion | HandlerInference;",
    "",
  ].join("\n");
}

export function verifyLargeFixtureGenerated(write: boolean): void {
  const expected = largeFixtureSource();
  if (write) {
    writeFileSync(fixturePath, expected);
    return;
  }
  const actual = readFileSync(fixturePath, "utf8");
  if (actual !== expected) {
    throw new Error("large-app.ts drifted; run pnpm desktop-contracts:generate");
  }
}

function digits(value: number, width: number): string {
  return String(value).padStart(width, "0");
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  try {
    verifyLargeFixtureGenerated(process.argv.includes("--write"));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`protocols-desktop-large-fixture: failed: ${message}`);
    process.exitCode = 1;
  }
}
